CREATE TABLE IF NOT EXISTS `anagrafica_view_static` (
  `id` int(11) NOT NULL,
  `codice` char(32) DEFAULT NULL,
  `id_tipologia` int(11) DEFAULT NULL,
  `nome` char(64) DEFAULT NULL,
  `cognome` char(255) DEFAULT NULL,
  `denominazione` char(255) DEFAULT NULL,
  `soprannome` char(128) DEFAULT NULL,
  `sesso` enum('M','F','-') NOT NULL DEFAULT '-',
  `id_orientamento_sessuale` int(11) DEFAULT NULL,
  `codice_fiscale` char(32) DEFAULT NULL,
  `partita_iva` char(32) DEFAULT NULL,
  `codice_sdi` char(32) DEFAULT NULL,
  `id_pec_sdi` int(11) DEFAULT NULL,
  `id_regime_fiscale` int(11) DEFAULT NULL,
  `note_amministrative` text,
  `luogo_nascita` char(128) DEFAULT NULL,
  `stato_nascita` char(128) DEFAULT NULL,
  `id_stato_nascita` int(11) DEFAULT NULL,
  `comune_nascita` int(11) DEFAULT NULL,
  `giorno_nascita` int(2) DEFAULT NULL,
  `mese_nascita` int(2) DEFAULT NULL,
  `anno_nascita` int(4) DEFAULT NULL,
  `id_diritto` int(11) DEFAULT NULL,
  `id_tipologia_crm` int(11) DEFAULT NULL,
  `id_agente` int(11) DEFAULT NULL,
  `note_commerciali` text,
  `condizioni_vendita` text,
  `condizioni_acquisto` text,
  `note` text,
  `data_cessazione` date DEFAULT NULL,
  `note_cessazione` text,
  `recapiti` text,
  `id_account_inserimento` int(11) DEFAULT NULL,
  `se_importata` int(1) DEFAULT NULL,
  `se_stampa_privacy` int(1) DEFAULT NULL,
  `timestamp_inserimento` int(11) DEFAULT NULL,
  `id_account_aggiornamento` int(11) DEFAULT NULL,
  `timestamp_aggiornamento` int(11) DEFAULT NULL,
  `pec_sdi` text,
  `sigla_stato` text,
  `cittadinanze` text,
  `se_collaboratore` int(1) DEFAULT NULL,
  `se_dipendente` int(1) DEFAULT NULL,
  `se_interinale` int(1) DEFAULT NULL,
  `se_cliente` int(1) DEFAULT NULL,
  `se_lead` int(1) DEFAULT NULL,
  `se_prospect` int(1) DEFAULT NULL,
  `se_mandante` int(1) DEFAULT NULL,
  `se_fornitore` int(1) DEFAULT NULL,
  `se_produttore` int(1) DEFAULT NULL,
  `se_agente` int(1) DEFAULT NULL,
  `se_interno` int(1) DEFAULT NULL,
  `se_esterno` int(1) DEFAULT NULL,
  `se_amministrazione` int(1) DEFAULT NULL,
  `se_azienda_gestita` int(1) DEFAULT NULL,
  `se_concorrente` int(1) DEFAULT NULL,
  `se_tutor` int(1) DEFAULT NULL,
  `se_classe` int(1) DEFAULT NULL,
  `se_docente` int(1) DEFAULT NULL,
  `se_allievo` int(1) DEFAULT NULL,
  `__label__` char(255) DEFAULT NULL,
  `denominazione_fiscale` char(255) DEFAULT NULL,
  `diritto` char(255) DEFAULT NULL,
  `agente` char(255) DEFAULT NULL,
  `categorie` text,
  `telefoni` text,
  `mail` text,
  `specialita` text,
  `provincia` text,
  `codice_regime_fiscale` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8;