CREATE TABLE IF NOT EXISTS `attivita_view_static` (
`id` int(11) NOT NULL,
  `id_tipologia` int(11) DEFAULT NULL,
  `tipologia` char(64) DEFAULT NULL,
  `id_tipologia_inps` int(11) DEFAULT NULL,  
  `tipologia_inps` char(255) DEFAULT NULL,  
  `id_anagrafica` int(11) DEFAULT NULL,  
  `anagrafica` varchar(320) DEFAULT NULL, 
  `id_mandante` int(11) DEFAULT NULL,
  `mandante` text,
  `id_cliente` int(11) DEFAULT NULL,  
  `cliente` varchar(320) DEFAULT NULL,
  `id_luogo` int(11) DEFAULT NULL,
  `id_indirizzo` int(11) DEFAULT NULL,  
  `indirizzo` text,
  `latitudine_ora_inizio` decimal(11,7) DEFAULT NULL,
  `longitudine_ora_inizio` decimal(11,7) DEFAULT NULL,
  `latitudine_ora_fine` decimal(11,7) DEFAULT NULL,
  `longitudine_ora_fine` decimal(11,7) DEFAULT NULL,
  `id_categoria_prodotti` int(11) DEFAULT NULL,  
  `data` date DEFAULT NULL,
  `data_attivita` date DEFAULT NULL,
  `ora` time DEFAULT NULL,
  `ora_inizio` time DEFAULT NULL,
  `ora_fine` time DEFAULT NULL,  
  `token` char(128) DEFAULT NULL,  
  `data_programmazione` date DEFAULT NULL,
  `ora_inizio_programmazione` time DEFAULT NULL,
  `ora_fine_programmazione` time DEFAULT NULL,
  `id_pianificazione` int(11) DEFAULT NULL,
  `id_pratica` int(11) DEFAULT NULL,
  `pratica` varchar(277) DEFAULT NULL,
  `id_progetto` char(32) DEFAULT NULL,
  `progetto` char(255) DEFAULT NULL, 
  `referenti` text,
  `id_campagna` int(11) DEFAULT NULL,
  `id_task` int(11) DEFAULT NULL,
  `task` char(255) DEFAULT NULL,
  `id_todo` int(11) DEFAULT NULL,
  `todo` char(255) DEFAULT NULL, 
  `id_tipologia_interesse` int(11) DEFAULT NULL,
  `id_tipologia_soddisfazione` int(11) DEFAULT NULL,
  `note_feedback` text,
  `id_immobile` int(11) DEFAULT NULL,
  `id_incarico` int(11) DEFAULT NULL,
  `id_richiesta` int(11) DEFAULT NULL,
  `id_incrocio_immobile` int(11) DEFAULT NULL,
  `nome` char(255) NOT NULL,
  `testo` text,
  `categorie_progetto` text,
  `timestamp_scadenza` int(11) DEFAULT NULL,
  `data_scadenza` date DEFAULT NULL,
  `ora_scadenza` time DEFAULT NULL,
  `note_scadenza` text,
  `id_attivita_completamento` int(11) DEFAULT NULL,
  `ore` decimal(5,2) DEFAULT NULL,
  `id_esito` int(11) DEFAULT NULL,
  `id_account_editor` int(11) DEFAULT NULL,
  `id_account_inserimento` int(11) DEFAULT NULL,
  `timestamp_inserimento` int(11) DEFAULT NULL,
  `id_account_aggiornamento` int(11) DEFAULT NULL,
  `timestamp_aggiornamento` int(11) DEFAULT NULL,
  `giorno` int(2) DEFAULT NULL,
  `mese` int(2) DEFAULT NULL,
  `anno` int(4) DEFAULT NULL,
  `ore_previste_task` decimal(5,2) DEFAULT NULL,
  `ore_previste_todo` decimal(5,2) DEFAULT NULL,
  `icona_html` char(8) DEFAULT NULL,
  `icona_fa` char(8) DEFAULT NULL,  
  `tipologia_attivita_immobiliare` varchar(11) DEFAULT NULL, 
  `id_mastro_provenienza` int(11) DEFAULT NULL,  
  `mastro_provenienza` char(64) DEFAULT NULL, 
  `id_mastro_destinazione` int(11) DEFAULT NULL,
  `mastro_destinazione` char(64) DEFAULT NULL,
  `__label__` varchar(320) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;