INSERT INTO `ruoli_immagini` (`id`, `nome`, `se_contenuti`, `se_anagrafica`, `se_immobili`, `se_catalogo`, `se_prodotti`, `ordine_scalamento`, `se_categorie_prodotti`, `se_articoli`) VALUES
(1, 'intestazione', 1, NULL, NULL, 1, 1, 300, NULL, 1),
(2, 'sfondo', 1, NULL, NULL, NULL, NULL, 900, NULL, NULL),
(3, 'thumbnail', 1, NULL, NULL, 1, 1, 900, NULL, NULL),
(4, 'card', 1, NULL, NULL, 1, 1, 200, NULL, 1),
(5, 'media', NULL, NULL, NULL, 1, 1, 900, NULL, 1),
(6, 'icona', 1, NULL, NULL, NULL, NULL, 900, NULL, NULL),
(7, 'gallery', 1, NULL, NULL, 1, 1, 700, NULL, 1),
(8, 'footer', 1, NULL, NULL, NULL, NULL, 900, NULL, NULL),
(9, 'contenuto', 1, NULL, NULL, 1, 1, 900, NULL, 1),
(10, 'copertina', 1, NULL, NULL, 1, 1, 900, NULL, NULL),
(11, 'principale', 1, NULL, 1, 1, 1, 600, NULL, NULL),
(12, 'carousel', 1, NULL, NULL, 1, 1, 100, NULL, 1),
(13, 'immagine', 1, 1, 1, 1, 1, 900, NULL, 1),
(14, 'jumbotron', 1, NULL, NULL, 1, 1, 900, NULL, NULL),
(15, 'dettaglio', NULL, NULL, NULL, 1, 1, 900, NULL, 1),
(16, 'anteprima', 1, NULL, NULL, 1, 1, 900, NULL, 1),
(17, 'avatar', NULL, 1, NULL, NULL, NULL, 900, NULL, NULL),
(18, 'logo', NULL, 1, NULL, NULL, NULL, 100, NULL, NULL),
(19, 'applicazione', NULL, NULL, NULL, NULL, NULL, 500, NULL, NULL),
(20, 'interno', NULL, NULL, 1, NULL, NULL, 900, NULL, NULL),
(21, 'esterno', NULL, NULL, 1, NULL, NULL, 900, NULL, NULL),
(25, 'campanelli', NULL, NULL, 1, NULL, NULL, 900, NULL, NULL),
(26, 'concorrenza', NULL, NULL, 1, NULL, NULL, 900, NULL, NULL),
(27, 'mappa', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(28, 'planimetria', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(29, 'bibliografia', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)ON DUPLICATE KEY UPDATE
    nome = VALUES( nome ),
    se_contenuti = VALUES( se_contenuti ),
    se_anagrafica = VALUES( se_anagrafica ),
    se_immobili = VALUES( se_immobili ),
    se_catalogo = VALUES( se_catalogo ),
    se_prodotti = VALUES( se_prodotti ),
    ordine_scalamento = VALUES( ordine_scalamento ),
    se_categorie_prodotti = VALUES( se_categorie_prodotti ),
    se_articoli = VALUES( se_articoli )
;