-- 
-- PATCH
--

--| 202206280015
 ALTER TABLE pianificazioni
 ADD COLUMN `model_id_anagrafica` int(11) DEFAULT NULL AFTER `entita`,
 ADD COLUMN `model_id_anagrafica_programmazione` int(11) DEFAULT  NULL AFTER `model_id_anagrafica`,
 ADD COLUMN `model_id_articolo` char(32) DEFAULT  NULL AFTER `model_id_anagrafica_programmazione`,
 ADD COLUMN `model_id_attivita` int(11) DEFAULT  NULL AFTER `model_id_articolo`,
 ADD COLUMN `model_id_causale` int(11) DEFAULT  NULL AFTER `model_id_attivita`,
 ADD COLUMN `model_id_cliente` int(11) DEFAULT  NULL AFTER `model_id_causale`,
 ADD COLUMN `model_id_collo` int(11) DEFAULT  NULL AFTER `model_id_cliente`,
 ADD COLUMN `model_id_condizione_pagamento` int(11) DEFAULT  NULL AFTER `model_id_collo`,
 ADD COLUMN `model_id_contatto` int(11) DEFAULT  NULL AFTER `model_id_condizione_pagamento`,
 ADD COLUMN `model_id_coupon` char(32) DEFAULT  NULL AFTER `model_id_contatto`,
 ADD COLUMN `model_id_destinatario` int(11) DEFAULT  NULL AFTER `model_id_coupon`,
 ADD COLUMN `model_id_documento` int(11) DEFAULT  NULL AFTER `model_id_destinatario`, 
 ADD COLUMN `model_id_emittente` int(11) DEFAULT  NULL AFTER `model_id_documento`,
 ADD COLUMN `model_id_genitore` int(11) DEFAULT  NULL AFTER `model_id_emittente`,
 ADD COLUMN `model_id_iban` int(11) DEFAULT  NULL AFTER `model_id_genitore`,
 ADD COLUMN `model_id_indirizzo` int(11) DEFAULT  NULL AFTER `model_id_iban`,
 ADD COLUMN `model_id_immobile` int(11) DEFAULT  NULL AFTER `model_id_indirizzo`,
 ADD COLUMN `model_id_licenza` int(11) DEFAULT  NULL AFTER `model_id_immobile`,
 ADD COLUMN `model_id_listino` int(11) DEFAULT  NULL AFTER `model_id_licenza`,
 ADD COLUMN `model_id_mastro_destinazione` int(11) DEFAULT NULL AFTER model_id_luogo,
 ADD COLUMN `model_id_mastro_provenienza` int(11) DEFAULT  NULL AFTER `model_id_mastro_destinazione`,
 ADD COLUMN `model_id_matricola` int(11) DEFAULT  NULL AFTER `model_id_mastro_provenienza`,
 ADD COLUMN `model_id_modalita_pagamento` int(11) DEFAULT  NULL AFTER `model_id_matricola`,
 ADD COLUMN `model_id_prodotto` char(32) DEFAULT  NULL AFTER `model_id_modalita_pagamento`,
 ADD COLUMN `model_id_progetto` char(32) DEFAULT  NULL AFTER `model_id_prodotto`,
 ADD COLUMN `model_id_reparto` int(11) DEFAULT  NULL AFTER `model_id_progetto`,
 ADD COLUMN `model_id_sede_destinatario` int(11) DEFAULT  NULL AFTER `model_id_reparto`,
 ADD COLUMN `model_id_sede_emittente` int(11) DEFAULT  NULL AFTER `model_id_sede_destinatario`,
 ADD COLUMN `model_id_tipologia` int(11) DEFAULT  NULL AFTER `model_id_sede_emittente`,
 ADD COLUMN `model_id_todo` int(11) DEFAULT  NULL AFTER `model_id_tipologia`,
 ADD COLUMN `model_id_trasportatore` int(11) DEFAULT  NULL AFTER `model_id_todo`,
 ADD COLUMN `model_id_udm` int(11) DEFAULT  NULL AFTER `model_id_trasportatore`,
 ADD COLUMN `model_anno_programmazione` year(4) DEFAULT  NULL AFTER `model_id_udm`,
 ADD COLUMN `model_codice` char(64) DEFAULT  NULL AFTER `model_anno_programmazione`,
 ADD COLUMN `model_data` date DEFAULT  NULL AFTER `model_codice`,
 ADD COLUMN `model_data_fine` date DEFAULT  NULL AFTER `model_data`,
 ADD COLUMN `model_data_inizio` date DEFAULT  NULL AFTER `model_data_fine`,
 ADD COLUMN `model_data_programmazione` date DEFAULT  NULL AFTER `model_data_inizio`,
 ADD COLUMN `model_esigibilita`	enum('I','D','S') DEFAULT  NULL AFTER `model_data_programmazione`,      
 ADD COLUMN `model_importo_netto_totale` decimal(9,2) DEFAULT  NULL AFTER `model_esigibilita`,
 ADD COLUMN `model_nome` char(255) DEFAULT  NULL AFTER `model_importo_netto_totale`,
 ADD COLUMN `model_note` text DEFAULT  NULL AFTER `model_nome`,
 ADD COLUMN `model_note_programmazione` text AFTER `model_note`,
 ADD COLUMN `model_numero` char(32) DEFAULT  NULL AFTER `model_note_programmazione`,
 ADD COLUMN `model_ore_programmazione` decimal(5,2) DEFAULT NULL AFTER model_ora_fine_programmazione,
 ADD COLUMN `model_porto` enum('franco','assegnato','-') DEFAULT  NULL AFTER `model_ore_programmazione`,
 ADD COLUMN `model_quantita` decimal(9,2) DEFAULT  NULL AFTER `model_porto`,
 ADD COLUMN `model_riferimento` char(255) DEFAULT  NULL AFTER `model_quantita`, 
 ADD COLUMN `model_sconto_percentuale` decimal(9,2) DEFAULT  NULL AFTER `model_riferimento`,
 ADD COLUMN `model_sconto_valore` decimal(9,2) DEFAULT  NULL AFTER `model_sconto_percentuale`,
 ADD COLUMN `model_se_automatico` int(1) DEFAULT  NULL AFTER `model_sconto_valore`,
 ADD COLUMN `model_sezionale` char(32) DEFAULT  NULL AFTER `model_se_automatico`,
 ADD COLUMN `model_settimana_programmazione` int(11) DEFAULT  NULL AFTER `model_sezionale`,
 ADD COLUMN `model_specifiche` char(255) DEFAULT  NULL AFTER `model_settimana_programmazione`,
 ADD COLUMN `model_timestamp_scadenza` int(11) DEFAULT  NULL AFTER `model_specifiche`;


--| 202206280020
 ALTER TABLE pianificazioni
 ADD KEY `model_id_anagrafica`  (`model_id_anagrafica`),
 ADD KEY `model_id_anagrafica_programmazione`  (`model_id_anagrafica_programmazione`),
 ADD KEY `model_id_articolo`  (`model_id_articolo`),
 ADD KEY `model_id_attivita`  (`model_id_attivita`),
 ADD KEY `model_id_cliente`  (`model_id_cliente`),
 ADD KEY `model_id_condizione_pagamento`  (`model_id_condizione_pagamento`),
 ADD KEY `model_id_contatto`  (`model_id_contatto`),
 ADD KEY `model_id_coupon`  (`model_id_coupon`),
 ADD KEY `model_id_destinatario`  (`model_id_destinatario`),
 ADD KEY `model_id_documento`  (`model_id_documento`), 
 ADD KEY `model_id_emittente`  (`model_id_emittente`),
 ADD KEY `model_id_genitore`  (`model_id_genitore`),
 ADD KEY `model_id_iban`  (`model_id_iban`),
 ADD KEY `model_id_indirizzo`  (`model_id_indirizzo`),
 ADD KEY `model_id_immobile`  (`model_id_immobile`),
 ADD KEY `model_id_licenza`  (`model_id_licenza`),
 ADD KEY `model_id_listino`  (`model_id_listino`),
 ADD KEY `model_id_mastro_destinazione`  (`model_id_mastro_destinazione`),
 ADD KEY `model_id_mastro_provenienza`  (`model_id_mastro_provenienza`),
 ADD KEY `model_id_matricola`  (`model_id_matricola`),
 ADD KEY `model_id_modalita_pagamento`  (`model_id_modalita_pagamento`),
 ADD KEY `model_id_prodotto`  (`model_id_prodotto`),
 ADD KEY `model_id_progetto`  (`model_id_progetto`),
 ADD KEY `model_id_reparto`  (`model_id_reparto`),
 ADD KEY `model_id_tipologia`  (`model_id_tipologia`),
 ADD KEY `model_id_todo`  (`model_id_todo`),
 ADD KEY `model_id_trasportatore`  (`model_id_trasportatore`),
 ADD KEY `model_id_udm`  (`model_id_udm`),
 ADD KEY `model_anno_programmazione`  (`model_anno_programmazione`),
 ADD KEY `model_codice`  (`model_codice`),
 ADD KEY `model_data`  (`model_data`),
 ADD KEY `model_data_fine`  (`model_data_fine`),
 ADD KEY `model_data_inizio`  (`model_data_inizio`),
 ADD KEY `model_data_programmazione`  (`model_data_programmazione`),
 ADD KEY `model_importo_netto_totale`  (`model_importo_netto_totale`),
 ADD KEY `model_nome`  (`model_nome`),
 ADD KEY `model_ore_programmazione` (`model_ore_programmazione`),
 ADD KEY `model_quantita`  (`model_quantita`),
 ADD KEY `model_sconto_percentuale`  (`model_sconto_percentuale`),
 ADD KEY `model_sconto_valore`  (`model_sconto_valore`),
 ADD KEY `model_se_automatico`  (`model_se_automatico`),
 ADD KEY `model_sezionale`  (`model_sezionale`),
 ADD KEY `model_settimana_programmazione`  (`model_settimana_programmazione`),
 ADD KEY  `model_timestamp_scadenza`  (`model_timestamp_scadenza`);

--| 202206280031
CREATE OR REPLACE VIEW `pianificazioni_view` AS
	SELECT
		pianificazioni.id,
		pianificazioni.id_genitore,
		pianificazioni.id_progetto,
		pianificazioni.id_todo,
		pianificazioni.id_attivita,
		pianificazioni.id_contratto,
		pianificazioni.nome,
		pianificazioni.id_periodicita,
		periodicita.nome AS periodicita,
		pianificazioni.cadenza,
		pianificazioni.se_lunedi,
		pianificazioni.se_martedi,
		pianificazioni.se_mercoledi,
		pianificazioni.se_giovedi,
		pianificazioni.se_venerdi,
		pianificazioni.se_sabato,
		pianificazioni.se_domenica,
		pianificazioni.schema_ripetizione,
		pianificazioni.data_elaborazione,
		pianificazioni.giorni_estensione,
		pianificazioni.data_fine,
		pianificazioni.entita,
		pianificazioni.model_id_anagrafica,
		pianificazioni.model_id_anagrafica_programmazione,
		pianificazioni.model_id_articolo,
		pianificazioni.model_id_attivita,
		pianificazioni.model_id_causale,
		pianificazioni.model_id_cliente,
		pianificazioni.model_id_collo,
		pianificazioni.model_id_condizione_pagamento,
		pianificazioni.model_id_contatto,
		pianificazioni.model_id_coupon,
		pianificazioni.model_id_destinatario,
		pianificazioni.model_id_documento, 
		pianificazioni.model_id_emittente,
		pianificazioni.model_id_genitore,
		pianificazioni.model_id_iban,
		pianificazioni.model_id_indirizzo,
		pianificazioni.model_id_immobile,
		pianificazioni.model_id_licenza,
		pianificazioni.model_id_listino,
		pianificazioni.model_id_mastro_destinazione,
		pianificazioni.model_id_mastro_provenienza,
		pianificazioni.model_id_matricola,
		pianificazioni.model_id_modalita_pagamento,
		pianificazioni.model_id_prodotto,
		pianificazioni.model_id_progetto,
		pianificazioni.model_id_reparto,
		pianificazioni.model_id_sede_destinatario,
		pianificazioni.model_id_sede_emittente,
		pianificazioni.model_id_tipologia,
		pianificazioni.model_id_todo,
		pianificazioni.model_id_trasportatore,
		pianificazioni.model_id_udm,
		pianificazioni.model_anno_programmazione,
		pianificazioni.model_codice,
		pianificazioni.model_data,
		pianificazioni.model_data_fine,
		pianificazioni.model_data_inizio,
		pianificazioni.model_data_programmazione,
		pianificazioni.model_esigibilita,      
		pianificazioni.model_importo_netto_totale,
		pianificazioni.model_nome,
		pianificazioni.model_note,
		pianificazioni.model_note_programmazione,
		pianificazioni.model_numero,
		pianificazioni.model_ore_programmazione,
		pianificazioni.model_porto,
		pianificazioni.model_quantita,
		pianificazioni.model_riferimento, 
		pianificazioni.model_sconto_percentuale,
		pianificazioni.model_sconto_valore,
		pianificazioni.model_se_automatico,
		pianificazioni.model_sezionale,
		pianificazioni.model_settimana_programmazione,
		pianificazioni.model_specifiche,
		pianificazioni.model_timestamp_scadenza,
		pianificazioni.model_id_luogo,
		pianificazioni.model_ora_inizio_programmazione,
		pianificazioni.model_ora_fine_programmazione,
		pianificazioni.workspace,
		pianificazioni.token,
		pianificazioni.id_account_inserimento,
		pianificazioni.id_account_aggiornamento,
		concat_ws(
			' ',
			pianificazioni.nome,
			periodicita.nome,
			pianificazioni.cadenza
		) as __label__
	FROM pianificazioni
		LEFT JOIN periodicita ON periodicita.id = pianificazioni.id_periodicita
;

--| FINE