-- 2026-10-01 — le colonne che mancano alle tabelle che _202609291900.tabelle.riallineamento.sql trova gia' presenti
--
-- COSA SI VEDEVA. _202609291900.tabelle.riallineamento.sql crea le tabelle con CREATE TABLE IF NOT EXISTS e poi le
-- viste con CREATE VIEW IF NOT EXISTS. Su un deploy installato prima di marzo molte di quelle tabelle ci sono gia',
-- in una forma piu' vecchia, e la CREATE TABLE non le tocca; le viste che sul deploy mancano nascono invece sopra le
-- tabelle vecchie, leggono colonne che non ci sono e il task si ferma ( 1054 Unknown column, p.es.
-- certificazioni.se_identificazione in certificazioni_view ). Su un deploy sono mancate 39 colonne in 12 tabelle.
--
-- COSA FA. Prima del riallineamento, per ogni colonna delle CREATE TABLE di quella patch: se la tabella c'e' e la
-- colonna no, la aggiunge con la definizione della CREATE. Le tabelle che non ci sono le crea poi il riallineamento,
-- gia' complete. Una colonna aggiunta nasce vuota: se sul deploy lo stesso dato stava in una colonna con un altro
-- nome, la vista lo mostra vuoto finche' qualcuno non lo copia, quindi ogni colonna aggiunta si scrive in
-- @colonne_riallineamento_note, insieme a quelle che non si sono potute aggiungere, e il blocco prima della pulizia
-- la restituisce a chi applica la patch a mano. La procedura, e non un PREPARE nel blocco, per la ragione scritta in
-- _202609300900.colonne.tabelle.viste.sql.
--
-- I deploy che hanno gia' passato il riallineamento non leggono questo file: dove mancavano colonne, il task si e'
-- fermato e le si e' aggiunte a mano.
--
-- IDEMPOTENTE: ADD COLUMN solo dove la colonna manca; la tabella di lavoro si svuota prima di riempirla.

-- | 202609291850

-- la tabella di lavoro: le colonne delle CREATE TABLE del riallineamento
CREATE TABLE IF NOT EXISTS `__patch_colonne_riallineamento__` (
  `tabella` char(64) NOT NULL,
  `colonna` char(64) NOT NULL,
  `definizione` text NOT NULL,
  PRIMARY KEY (`tabella`,`colonna`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- | 202609291851

TRUNCATE TABLE `__patch_colonne_riallineamento__`;

-- | 202609291852

REPLACE INTO `__patch_colonne_riallineamento__` ( `tabella`, `colonna`, `definizione` ) VALUES
	( 'anagrafica_certificazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'anagrafica_certificazioni', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'id_certificazione', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'id_emittente', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'nome', 'char(1) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'codice', 'char(32) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'data_emissione', 'date DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'data_scadenza', 'date DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'note', 'text DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_certificazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'anagrafica_cittadinanze', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'id_stato', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'data_inizio', 'date DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'data_fine', 'date DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_cittadinanze', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'anagrafica_consensi', 'id_account', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'id_consenso', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'se_prestato', 'tinyint(1) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'note', 'text DEFAULT NULL' ),
	( 'anagrafica_consensi', 'timestamp_consenso', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_consensi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'anagrafica_progetti', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id_todo', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'nome', 'char(255) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'note', 'text DEFAULT NULL' ),
	( 'anagrafica_progetti', 'se_attesa', 'tinyint(1) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'se_sostituto', 'tinyint(1) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'note_inserimento', 'text NULL' ),
	( 'anagrafica_progetti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'note_aggiornamento', 'text NULL' ),
	( 'anagrafica_progetti', 'timestamp_archiviazione', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'id_account_archiviazione', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_progetti', 'note_archiviazione', 'text NULL' ),
	( 'anagrafica_settori', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'anagrafica_settori', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_settori', 'id_settore', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_settori', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_settori', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_settori', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'anagrafica_settori', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'anagrafica_settori', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'annunci', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'annunci', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'nome', 'char(255) DEFAULT NULL' ),
	( 'annunci', 'testo', 'text DEFAULT NULL' ),
	( 'annunci', 'id_categoria_prodotti', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'id_prodotto', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'quantita', 'decimal(9,2) DEFAULT NULL' ),
	( 'annunci', 'id_udm', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'data_inizio_validita', 'date DEFAULT NULL' ),
	( 'annunci', 'ora_inizio_validita', 'time DEFAULT NULL' ),
	( 'annunci', 'note_inizio_validita', 'text DEFAULT NULL' ),
	( 'annunci', 'data_fine_validita', 'date DEFAULT NULL' ),
	( 'annunci', 'ora_fine_validita', 'time DEFAULT NULL' ),
	( 'annunci', 'note_fine_validita', 'text DEFAULT NULL' ),
	( 'annunci', 'note', 'text DEFAULT NULL' ),
	( 'annunci', 'template', 'char(255) DEFAULT NULL' ),
	( 'annunci', 'schema_html', 'char(128) DEFAULT NULL' ),
	( 'annunci', 'tema_css', 'char(128) DEFAULT NULL' ),
	( 'annunci', 'se_sitemap', 'tinyint(1) DEFAULT NULL' ),
	( 'annunci', 'se_cacheable', 'tinyint(1) DEFAULT NULL' ),
	( 'annunci', 'id_sito', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'annunci', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'annunci', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'annunci_categorie', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'annunci_categorie', 'id_annuncio', 'bigint(20) DEFAULT NULL' ),
	( 'annunci_categorie', 'id_categoria', 'bigint(20) DEFAULT NULL' ),
	( 'annunci_categorie', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'annunci_categorie', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'annunci_categorie', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'annunci_categorie', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'annunci_categorie', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'badge', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'badge', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'badge', 'id_contratto', 'bigint(20) DEFAULT NULL' ),
	( 'badge', 'codice', 'char(32) DEFAULT NULL' ),
	( 'badge', 'rfid', 'char(32) DEFAULT NULL' ),
	( 'badge', 'nome', 'char(255) DEFAULT NULL' ),
	( 'badge', 'note', 'text NULL' ),
	( 'badge', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'badge', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'badge', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'badge', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'banner', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'banner', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'banner', 'id_sito', 'bigint(20) DEFAULT NULL' ),
	( 'banner', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'banner', 'nome', 'char(255) DEFAULT NULL' ),
	( 'banner', 'id_inserzionista', 'bigint(20) DEFAULT NULL' ),
	( 'banner', 'altezza_modulo', 'int(11) DEFAULT NULL' ),
	( 'banner', 'larghezza_modulo', 'int(11) DEFAULT NULL' ),
	( 'banner', 'token', 'char(128) DEFAULT NULL' ),
	( 'banner', 'note', 'text DEFAULT NULL' ),
	( 'banner', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'banner', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'banner', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'banner', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_azioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'banner_azioni', 'id_pagina', 'bigint(20) DEFAULT NULL' ),
	( 'banner_azioni', 'id_banner', 'bigint(20) DEFAULT NULL' ),
	( 'banner_azioni', 'azione', 'enum(''visualizzazione'',''click'') DEFAULT NULL' ),
	( 'banner_azioni', 'timestamp_azione', 'int(11) DEFAULT NULL' ),
	( 'banner_azioni', 'token', 'char(128) DEFAULT NULL' ),
	( 'banner_azioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_azioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'banner_azioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_azioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'banner_pagine', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'banner_pagine', 'id_pagina', 'bigint(20) DEFAULT NULL' ),
	( 'banner_pagine', 'id_banner', 'bigint(20) DEFAULT NULL' ),
	( 'banner_pagine', 'se_presente', 'tinyint(1) DEFAULT NULL' ),
	( 'banner_pagine', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_pagine', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'banner_pagine', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_pagine', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'banner_zone', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'banner_zone', 'id_zona', 'bigint(20) DEFAULT NULL' ),
	( 'banner_zone', 'id_banner', 'bigint(20) DEFAULT NULL' ),
	( 'banner_zone', 'se_presente', 'tinyint(1) DEFAULT NULL' ),
	( 'banner_zone', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_zone', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'banner_zone', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'banner_zone', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'campagne', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'campagne', 'nome', 'char(128) DEFAULT NULL' ),
	( 'campagne', 'note', 'text DEFAULT NULL' ),
	( 'campagne', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'campagne', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'campagne', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'campagne', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'carrelli_consensi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'carrelli_consensi', 'id_account', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_consensi', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_consensi', 'id_carrello', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_consensi', 'id_consenso', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_consensi', 'se_prestato', 'tinyint(1) DEFAULT NULL' ),
	( 'carrelli_consensi', 'note', 'text DEFAULT NULL' ),
	( 'carrelli_consensi', 'timestamp_consenso', 'int(11) DEFAULT NULL' ),
	( 'carrelli_consensi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_consensi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'carrelli_consensi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_consensi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'carrelli_documenti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'carrelli_documenti', 'id_carrello', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_documenti', 'id_documento', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_documenti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_documenti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'carrelli_documenti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'carrelli_documenti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'categorie_annunci', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'categorie_annunci', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_annunci', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'categorie_annunci', 'codice', 'char(32) DEFAULT NULL' ),
	( 'categorie_annunci', 'nome', 'char(255) DEFAULT NULL' ),
	( 'categorie_annunci', 'note', 'text DEFAULT NULL' ),
	( 'categorie_annunci', 'template', 'char(255) DEFAULT NULL' ),
	( 'categorie_annunci', 'schema_html', 'char(128) DEFAULT NULL' ),
	( 'categorie_annunci', 'tema_css', 'char(128) DEFAULT NULL' ),
	( 'categorie_annunci', 'se_sitemap', 'tinyint(1) DEFAULT NULL' ),
	( 'categorie_annunci', 'se_cacheable', 'tinyint(1) DEFAULT NULL' ),
	( 'categorie_annunci', 'id_sito', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_annunci', 'id_pagina', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_annunci', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_annunci', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'categorie_annunci', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_annunci', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'categorie_risorse', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'categorie_risorse', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_risorse', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'categorie_risorse', 'codice', 'char(32) DEFAULT NULL' ),
	( 'categorie_risorse', 'nome', 'char(64) DEFAULT NULL' ),
	( 'categorie_risorse', 'note', 'text DEFAULT NULL' ),
	( 'categorie_risorse', 'template', 'char(255) DEFAULT NULL' ),
	( 'categorie_risorse', 'schema_html', 'char(128) DEFAULT NULL' ),
	( 'categorie_risorse', 'tema_css', 'char(128) DEFAULT NULL' ),
	( 'categorie_risorse', 'se_sitemap', 'tinyint(1) DEFAULT NULL' ),
	( 'categorie_risorse', 'se_cacheable', 'tinyint(1) DEFAULT NULL' ),
	( 'categorie_risorse', 'id_sito', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_risorse', 'id_pagina', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_risorse', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_risorse', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'categorie_risorse', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'categorie_risorse', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'causali', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'causali', 'nome', 'char(64) NOT NULL' ),
	( 'causali', 'se_trasporto', 'tinyint(1) DEFAULT NULL' ),
	( 'causali', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'causali', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'causali', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'causali', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'certificazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'certificazioni', 'nome', 'char(255) DEFAULT NULL' ),
	( 'certificazioni', 'se_identificazione', 'tinyint(1) DEFAULT NULL' ),
	( 'certificazioni', 'se_medico', 'tinyint(1) DEFAULT NULL' ),
	( 'certificazioni', 'se_sportivo', 'tinyint(1) DEFAULT NULL' ),
	( 'certificazioni', 'se_agonistico', 'tinyint(1) DEFAULT NULL' ),
	( 'certificazioni', 'se_immobili', 'tinyint(1) DEFAULT NULL' ),
	( 'certificazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'certificazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'certificazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'certificazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'chiavi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'chiavi', 'id_licenza', 'bigint(20) DEFAULT NULL' ),
	( 'chiavi', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'chiavi', 'codice', 'char(32) DEFAULT NULL' ),
	( 'chiavi', 'seriale', 'char(32) DEFAULT NULL' ),
	( 'chiavi', 'nome', 'char(32) DEFAULT NULL' ),
	( 'chiavi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'chiavi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'chiavi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'chiavi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'classi_energetiche', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'classi_energetiche', 'nome', 'char(8) DEFAULT NULL' ),
	( 'classi_energetiche', 'ep_min', 'int(11) DEFAULT NULL' ),
	( 'classi_energetiche', 'ep_max', 'int(11) DEFAULT NULL' ),
	( 'classi_energetiche', 'rgb', 'char(8) DEFAULT NULL' ),
	( 'colori', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'colori', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'colori', 'nome', 'char(16) DEFAULT NULL' ),
	( 'colori', 'hex', 'char(8) DEFAULT NULL' ),
	( 'colori', 'r', 'int(3) DEFAULT NULL' ),
	( 'colori', 'g', 'int(3) DEFAULT NULL' ),
	( 'colori', 'b', 'int(3) DEFAULT NULL' ),
	( 'colori', 'ral', 'char(16) DEFAULT NULL' ),
	( 'colori', 'pantone', 'char(8) DEFAULT NULL' ),
	( 'colori', 'c', 'decimal(5,2) DEFAULT NULL' ),
	( 'colori', 'm', 'decimal(5,2) DEFAULT NULL' ),
	( 'colori', 'y', 'decimal(5,2) DEFAULT NULL' ),
	( 'colori', 'k', 'decimal(5,2) DEFAULT NULL' ),
	( 'colori', 'css', 'text DEFAULT NULL' ),
	( 'condizioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'condizioni', 'nome', 'char(32) DEFAULT NULL' ),
	( 'condizioni', 'se_catalogo', 'tinyint(1) DEFAULT NULL' ),
	( 'condizioni', 'se_immobili', 'tinyint(1) DEFAULT NULL' ),
	( 'contratti_progetti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'contratti_progetti', 'id_contratto', 'bigint(20) DEFAULT NULL' ),
	( 'contratti_progetti', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'contratti_progetti', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'contratti_progetti', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'contratti_progetti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'contratti_progetti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'contratti_progetti', 'note_inserimento', 'text NULL' ),
	( 'contratti_progetti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'contratti_progetti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'contratti_progetti', 'note_aggiornamento', 'text NULL' ),
	( 'contratti_progetti', 'timestamp_archiviazione', 'int(11) DEFAULT NULL' ),
	( 'contratti_progetti', 'id_account_archiviazione', 'bigint(20) DEFAULT NULL' ),
	( 'contratti_progetti', 'note_archiviazione', 'text NULL' ),
	( 'conversazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'conversazioni', 'id_annuncio', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'codice', 'char(32) DEFAULT NULL' ),
	( 'conversazioni', 'nome', 'char(255) DEFAULT NULL' ),
	( 'conversazioni', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'quantita', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'note', 'text DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_apertura', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_chiusura', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'conversazioni', 'id_conversazione', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'id_account', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_lettura', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_entrata', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_uscita', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'conversazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'conversazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'coupon_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'coupon_articoli', 'id_coupon', 'bigint(20) NOT NULL' ),
	( 'coupon_articoli', 'id_articolo', 'bigint(20) NOT NULL' ),
	( 'coupon_articoli', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'coupon_articoli', 'gruppo_alternative', 'char(32) NOT NULL' ),
	( 'coupon_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'coupon_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'coupon_categorie_prodotti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'coupon_categorie_prodotti', 'id_coupon', 'bigint(20) NOT NULL' ),
	( 'coupon_categorie_prodotti', 'id_categoria', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_categorie_prodotti', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'coupon_categorie_prodotti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_categorie_prodotti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'coupon_categorie_prodotti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_categorie_prodotti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'coupon_listini', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'coupon_listini', 'id_coupon', 'bigint(20) NOT NULL' ),
	( 'coupon_listini', 'id_listino', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_listini', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'coupon_listini', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_listini', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'coupon_listini', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_listini', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'coupon_marchi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'coupon_marchi', 'id_coupon', 'bigint(20) NOT NULL' ),
	( 'coupon_marchi', 'id_marchio', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_marchi', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'coupon_marchi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_marchi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'coupon_marchi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_marchi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'coupon_prodotti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'coupon_prodotti', 'id_coupon', 'bigint(20) NOT NULL' ),
	( 'coupon_prodotti', 'id_prodotto', 'bigint(20) NOT NULL' ),
	( 'coupon_prodotti', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'coupon_prodotti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_prodotti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'coupon_prodotti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'coupon_prodotti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'crediti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'crediti', 'id_documenti_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'id_mastro_provenienza', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'id_mastro_destinazione', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'id_account_destinatario', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'id_account_emittente', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'id_pianificazione', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'data', 'date DEFAULT NULL' ),
	( 'crediti', 'quantita', 'decimal(9,2) DEFAULT NULL' ),
	( 'crediti', 'nome', 'char(255) DEFAULT NULL' ),
	( 'crediti', 'note', 'text DEFAULT NULL' ),
	( 'crediti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'crediti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'crediti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'disponibilita', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'disponibilita', 'nome', 'char(32) DEFAULT NULL' ),
	( 'disponibilita', 'se_catalogo', 'tinyint(1) DEFAULT NULL' ),
	( 'disponibilita', 'se_immobili', 'tinyint(1) DEFAULT NULL' ),
	( 'edifici', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'edifici', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'edifici', 'id_indirizzo', 'bigint(20) DEFAULT NULL' ),
	( 'edifici', 'codice', 'char(32) DEFAULT NULL' ),
	( 'edifici', 'nome', 'char(128) DEFAULT NULL' ),
	( 'edifici', 'piani', 'int(11) DEFAULT NULL' ),
	( 'edifici', 'note', 'text DEFAULT NULL' ),
	( 'edifici', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'edifici', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'edifici', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'edifici', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'edifici_caratteristiche', 'id_edificio', 'bigint(20) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'id_caratteristica', 'bigint(20) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'se_presente', 'tinyint(1) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'note', 'text DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'edifici_caratteristiche', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'giorni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'giorni', 'nome', 'char(12) DEFAULT NULL' ),
	( 'immobili', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'immobili', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'immobili', 'id_edificio', 'bigint(20) DEFAULT NULL' ),
	( 'immobili', 'codice', 'char(32) DEFAULT NULL' ),
	( 'immobili', 'nome', 'char(32) DEFAULT NULL' ),
	( 'immobili', 'scala', 'char(32) DEFAULT NULL' ),
	( 'immobili', 'piano', 'char(64) DEFAULT NULL' ),
	( 'immobili', 'interno', 'char(8) DEFAULT NULL' ),
	( 'immobili', 'campanello', 'char(128) DEFAULT NULL' ),
	( 'immobili', 'catasto_foglio', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_particella', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_sub', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_categoria', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_classe', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_consistenza', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_superficie', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'catasto_rendita', 'char(255) DEFAULT NULL' ),
	( 'immobili', 'note', 'text DEFAULT NULL' ),
	( 'immobili', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'immobili', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'immobili', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'immobili', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'immobili_anagrafica', 'id_immobile', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'note', 'text DEFAULT NULL' ),
	( 'immobili_anagrafica', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'immobili_anagrafica', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'immobili_caratteristiche', 'id_immobile', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'id_caratteristica', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'se_presente', 'tinyint(1) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'note', 'text DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'immobili_caratteristiche', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'indirizzi_caratteristiche', 'id_indirizzo', 'bigint(20) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'id_caratteristica', 'bigint(20) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'se_presente', 'tinyint(1) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'note', 'text DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'indirizzi_caratteristiche', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'licenze_software', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'licenze_software', 'id_licenza', 'bigint(20) DEFAULT NULL' ),
	( 'licenze_software', 'id_software', 'bigint(20) DEFAULT NULL' ),
	( 'licenze_software', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'licenze_software', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'licenze_software', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'licenze_software', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'licenze_software', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'liste', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'liste', 'nome', 'char(255) DEFAULT NULL' ),
	( 'liste', 'note', 'text DEFAULT NULL' ),
	( 'liste', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'liste', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'liste', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'liste', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'liste_mail', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'liste_mail', 'id_lista', 'bigint(20) DEFAULT NULL' ),
	( 'liste_mail', 'id_mail', 'bigint(20) DEFAULT NULL' ),
	( 'liste_mail', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'liste_mail', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'liste_mail', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'liste_mail', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'listini_clienti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'listini_clienti', 'id_listino', 'bigint(20) DEFAULT NULL' ),
	( 'listini_clienti', 'id_cliente', 'bigint(20) DEFAULT NULL' ),
	( 'listini_clienti', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'listini_clienti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'listini_clienti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'listini_clienti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'listini_clienti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'luoghi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'luoghi', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'id_indirizzo', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'id_edificio', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'id_immobile', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'url', 'char(255) DEFAULT NULL' ),
	( 'luoghi', 'nome', 'char(255) DEFAULT NULL' ),
	( 'luoghi', 'note', 'text DEFAULT NULL' ),
	( 'luoghi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'luoghi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'luoghi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'mailing', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'mailing', 'nome', 'char(255) DEFAULT NULL' ),
	( 'mailing', 'note', 'text DEFAULT NULL' ),
	( 'mailing', 'promemoria_id_tipologia', 'int(11) DEFAULT NULL' ),
	( 'mailing', 'promemoria_id_anagrafica_programmazione', 'int(11) DEFAULT NULL' ),
	( 'mailing', 'promemoria_nome', 'char(255) DEFAULT NULL' ),
	( 'mailing', 'promemoria_giorni_programmazione', 'int(11) DEFAULT NULL' ),
	( 'mailing', 'promemoria_note_programmazione', 'text DEFAULT NULL' ),
	( 'mailing', 'timestamp_invio', 'int(11) DEFAULT NULL' ),
	( 'mailing', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'mailing', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'mailing', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'mailing', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'mailing_liste', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'mailing_liste', 'id_mailing', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_liste', 'id_lista', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_liste', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_liste', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'mailing_liste', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_liste', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'mailing_mail', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'mailing_mail', 'id_mailing', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_mail', 'id_mail', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_mail', 'id_mail_out', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_mail', 'token', 'char(128) DEFAULT NULL' ),
	( 'mailing_mail', 'timestamp_generazione', 'int(11) DEFAULT NULL' ),
	( 'mailing_mail', 'timestamp_invio', 'int(11) DEFAULT NULL' ),
	( 'mailing_mail', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_mail', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'mailing_mail', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'mailing_mail', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'messaggi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'messaggi', 'id_conversazione', 'bigint(20) DEFAULT NULL' ),
	( 'messaggi', 'testo', 'text DEFAULT NULL' ),
	( 'messaggi', 'timestamp_invio', 'int(11) DEFAULT NULL' ),
	( 'messaggi', 'timestamp_lettura', 'int(11) DEFAULT NULL' ),
	( 'messaggi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'messaggi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'messaggi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'messaggi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'metadati_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'metadati_articoli', 'id_lingua', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_articoli', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_articoli', 'nome', 'char(128) DEFAULT NULL' ),
	( 'metadati_articoli', 'testo', 'text DEFAULT NULL' ),
	( 'metadati_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'metadati_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'metadati_prodotti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'metadati_prodotti', 'id_lingua', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_prodotti', 'id_prodotto', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_prodotti', 'nome', 'char(128) DEFAULT NULL' ),
	( 'metadati_prodotti', 'testo', 'text DEFAULT NULL' ),
	( 'metadati_prodotti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_prodotti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'metadati_prodotti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'metadati_prodotti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'orari', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'orari', 'nome', 'char(128) DEFAULT NULL' ),
	( 'orari', 'id_tipologia_contratti', 'bigint(20) DEFAULT NULL' ),
	( 'orari', 'id_periodicita', 'bigint(20) DEFAULT NULL' ),
	( 'orari', 'id_giorno', 'bigint(20) DEFAULT NULL' ),
	( 'orari', 'ora_inizio', 'time NULL' ),
	( 'orari', 'ora_fine', 'time NULL' ),
	( 'orari', 'note', 'text NULL' ),
	( 'orari', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'orari', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'orari', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'orari', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'periodi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'periodi', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'periodi', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'periodi', 'id_contratto', 'bigint(20) DEFAULT NULL' ),
	( 'periodi', 'data_inizio', 'date DEFAULT NULL' ),
	( 'periodi', 'data_fine', 'date DEFAULT NULL' ),
	( 'periodi', 'nome', 'char(128) DEFAULT NULL' ),
	( 'periodi', 'note', 'text DEFAULT NULL' ),
	( 'periodi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'periodi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'periodi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'periodi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'pesi_tipologie_corrispondenza', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'pesi_tipologie_corrispondenza', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'pesi_tipologie_corrispondenza', 'nome', 'varchar(128) DEFAULT NULL' ),
	( 'pesi_tipologie_corrispondenza', 'grammi_min', 'decimal(8,2) DEFAULT NULL' ),
	( 'pesi_tipologie_corrispondenza', 'grammi_max', 'decimal(8,2) DEFAULT NULL' ),
	( 'popup', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'popup', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'popup', 'id_sito', 'bigint(20) DEFAULT NULL' ),
	( 'popup', 'nome', 'char(128) DEFAULT NULL' ),
	( 'popup', 'note', 'text DEFAULT NULL' ),
	( 'popup', 'html_id', 'char(128) DEFAULT NULL' ),
	( 'popup', 'html_class', 'char(128) DEFAULT NULL' ),
	( 'popup', 'html_class_attivazione', 'char(128) DEFAULT NULL' ),
	( 'popup', 'n_scroll', 'int(11) DEFAULT NULL' ),
	( 'popup', 'n_secondi', 'int(11) DEFAULT NULL' ),
	( 'popup', 'template', 'char(128) DEFAULT NULL' ),
	( 'popup', 'schema_html', 'char(128) DEFAULT NULL' ),
	( 'popup', 'se_ovunque', 'tinyint(1) DEFAULT NULL' ),
	( 'popup', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'popup', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'popup', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'popup', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'popup_pagine', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'popup_pagine', 'id_pagina', 'bigint(20) DEFAULT NULL' ),
	( 'popup_pagine', 'id_popup', 'bigint(20) DEFAULT NULL' ),
	( 'popup_pagine', 'se_presente', 'tinyint(1) DEFAULT NULL' ),
	( 'popup_pagine', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'popup_pagine', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'popup_pagine', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'popup_pagine', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'progetti_anagrafica', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'nome', 'char(255) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'note', 'text DEFAULT NULL' ),
	( 'progetti_anagrafica', 'se_sostituto', 'tinyint(1) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'progetti_anagrafica', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'progetti_articoli', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_articoli', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_articoli', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_articoli', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'progetti_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'progetti_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'progetti_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'progetti_certificazioni', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'id_certificazione', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'nome', 'char(1) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'note', 'text DEFAULT NULL' ),
	( 'progetti_certificazioni', 'se_richiesta', 'tinyint(1) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_certificazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'progetti_matricole', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'progetti_matricole', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_matricole', 'id_matricola', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_matricole', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_matricole', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'progetti_matricole', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'progetti_matricole', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'progetti_matricole', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'progetti_matricole', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'redirect_azioni', 'id', 'bigint(20) NOT NULL ' ),
	( 'redirect_azioni', 'id_redirect', 'bigint(20) DEFAULT NULL' ),
	( 'redirect_azioni', 'referral', 'text DEFAULT NULL' ),
	( 'redirect_azioni', 'azione', 'enum(''redirect'') DEFAULT NULL' ),
	( 'redirect_azioni', 'timestamp_azione', 'int(11) DEFAULT NULL' ),
	( 'redirect_azioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'redirect_azioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'redirect_azioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'redirect_azioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'relazioni_articoli', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_prodotto_collegato', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_articolo_collegato', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'relazioni_articoli', 'id_categoria', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_categoria_collegata', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'relazioni_documenti_articoli', 'id_documenti_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'id_documenti_articolo_collegato', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_documenti_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_pagamenti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'relazioni_pagamenti', 'id_pagamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_pagamenti', 'id_pagamento_collegato', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_pagamenti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_pagamenti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_pagamenti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_pagamenti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_progetti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'relazioni_progetti', 'id_progetto', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_progetti', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_progetti', 'id_progetto_collegato', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_progetti', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_progetti', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_progetti', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_progetti', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_software', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'relazioni_software', 'id_software', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_software', 'id_software_collegato', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_software', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_software', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'relazioni_software', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'relazioni_software', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'rinnovi_documenti_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'rinnovi_documenti_articoli', 'id_rinnovo', 'bigint(20) DEFAULT NULL' ),
	( 'rinnovi_documenti_articoli', 'id_documenti_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'rinnovi_documenti_articoli', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'rinnovi_documenti_articoli', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'rinnovi_documenti_articoli', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'rinnovi_documenti_articoli', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'risorse', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'risorse', 'id_tipologia', 'bigint(20) DEFAULT NULL' ),
	( 'risorse', 'codice', 'char(32) DEFAULT NULL' ),
	( 'risorse', 'nome', 'char(64) DEFAULT NULL' ),
	( 'risorse', 'note', 'text DEFAULT NULL' ),
	( 'risorse', 'template', 'char(255) DEFAULT NULL' ),
	( 'risorse', 'schema_html', 'char(128) DEFAULT NULL' ),
	( 'risorse', 'tema_css', 'char(128) DEFAULT NULL' ),
	( 'risorse', 'se_sitemap', 'tinyint(1) DEFAULT NULL' ),
	( 'risorse', 'se_cacheable', 'tinyint(1) DEFAULT NULL' ),
	( 'risorse', 'id_sito', 'bigint(20) DEFAULT NULL' ),
	( 'risorse', 'id_testata', 'bigint(20) DEFAULT NULL' ),
	( 'risorse', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'risorse', 'id_prodotto', 'bigint(20) DEFAULT NULL' ),
	( 'risorse', 'giorno_pubblicazione', 'int(2) DEFAULT NULL' ),
	( 'risorse', 'mese_pubblicazione', 'int(2) DEFAULT NULL' ),
	( 'risorse', 'anno_pubblicazione', 'int(4) DEFAULT NULL' ),
	( 'risorse', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'risorse', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'risorse', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_account', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'risorse_account', 'id_risorsa', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_account', 'id_account', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_account', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'risorse_account', 'note', 'text DEFAULT NULL' ),
	( 'risorse_account', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'risorse_account', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_account', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'risorse_account', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'risorse_anagrafica', 'id_risorsa', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'risorse_anagrafica', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_categorie', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'risorse_categorie', 'id_risorsa', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_categorie', 'id_categoria', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_categorie', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'risorse_categorie', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'risorse_categorie', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'risorse_categorie', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'risorse_categorie', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'ruoli_articoli', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'ruoli_articoli', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'ruoli_articoli', 'nome', 'char(128) DEFAULT NULL' ),
	( 'ruoli_articoli', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'ruoli_articoli', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'ruoli_articoli', 'se_progetti', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_articoli', 'se_risorse', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_articoli', 'se_acquisto', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_articoli', 'se_rinnovo', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'ruoli_categorie_progetti', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'nome', 'char(32) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'se_recuperi', 'int(1) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'ruoli_categorie_progetti', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'nome', 'char(32) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'ruoli_categorie_progetti', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'ruoli_progetti', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'ruoli_progetti', 'id_genitore', 'bigint(20) NOT NULL' ),
	( 'ruoli_progetti', 'nome', 'char(128) DEFAULT NULL' ),
	( 'ruoli_progetti', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'ruoli_progetti', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'ruoli_progetti', 'se_sottoprogetto', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_progetti', 'se_proseguimento', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_progetti', 'se_sostituto', 'tinyint(1) DEFAULT NULL' ),
	( 'ruoli_progetti', 'se_attesa', 'tinyint(1) DEFAULT NULL' ),
	( 'software', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'software', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'software', 'id_articolo', 'bigint(20) DEFAULT NULL' ),
	( 'software', 'codice', 'char(32) DEFAULT NULL' ),
	( 'software', 'json', 'text DEFAULT NULL' ),
	( 'software', 'nome', 'char(128) DEFAULT NULL' ),
	( 'software', 'note', 'text DEFAULT NULL' ),
	( 'software', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'software', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'software', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'software', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'stati_lingue', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'stati_lingue', 'id_stato', 'bigint(20) DEFAULT NULL' ),
	( 'stati_lingue', 'id_lingua', 'bigint(20) DEFAULT NULL' ),
	( 'stati_lingue', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'testate', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'testate', 'nome', 'char(128) DEFAULT NULL' ),
	( 'testate', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'testate', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'testate', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'testate', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_annunci', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_annunci', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_annunci', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_annunci', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_annunci', 'sigla', 'char(32) DEFAULT NULL' ),
	( 'tipologie_annunci', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_annunci', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_annunci', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_annunci', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_annunci', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_annunci', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_badge', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_badge', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_badge', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_badge', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_badge', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_badge', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_badge', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_badge', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_badge', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_badge', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_banner', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_banner', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_banner', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_banner', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_banner', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_banner', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_banner', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_banner', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_banner', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_banner', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_chiavi', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'nome', 'char(32) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_chiavi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_edifici', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_edifici', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_edifici', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_edifici', 'nome', 'char(32) DEFAULT NULL' ),
	( 'tipologie_edifici', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_edifici', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_edifici', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_edifici', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_edifici', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_edifici', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_immobili', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_immobili', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_immobili', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_immobili', 'nome', 'char(32) DEFAULT NULL' ),
	( 'tipologie_immobili', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_immobili', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_immobili', 'se_residenziale', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_immobili', 'se_industriale', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_immobili', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_immobili', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_immobili', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_immobili', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_licenze', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_licenze', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_licenze', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_licenze', 'nome', 'char(32) DEFAULT NULL' ),
	( 'tipologie_licenze', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_licenze', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_licenze', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_licenze', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_licenze', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_licenze', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_luoghi', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_luoghi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_mastri', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_mastri', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_mastri', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_mastri', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_mastri', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_mastri', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_mastri', 'se_magazzino', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_mastri', 'se_conto', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_mastri', 'se_registro', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_mastri', 'se_credito', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_mastri', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_mastri', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_mastri', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_mastri', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_periodi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_periodi', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_periodi', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_periodi', 'codice', 'char(32) DEFAULT NULL' ),
	( 'tipologie_periodi', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_periodi', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_periodi', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_periodi', 'se_corsi', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_periodi', 'se_tesseramenti', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_periodi', 'se_abbonamenti', 'tinyint(1) DEFAULT NULL' ),
	( 'tipologie_periodi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_periodi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_periodi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_periodi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_popup', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_popup', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_popup', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_popup', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_popup', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_popup', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_popup', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_popup', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_popup', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_popup', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_risorse', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_risorse', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_risorse', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_risorse', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_risorse', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_risorse', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_risorse', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_risorse', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_risorse', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_risorse', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'tipologie_spedizioni', 'id_genitore', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'nome', 'char(64) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'html_entity', 'char(8) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'font_awesome', 'char(16) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'tipologie_spedizioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'todo_matricole', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'todo_matricole', 'id_todo', 'bigint(20) DEFAULT NULL' ),
	( 'todo_matricole', 'id_matricola', 'bigint(20) DEFAULT NULL' ),
	( 'todo_matricole', 'id_ruolo', 'bigint(20) DEFAULT NULL' ),
	( 'todo_matricole', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'todo_matricole', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'todo_matricole', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'todo_matricole', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'todo_matricole', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'valutazioni', 'id_anagrafica', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'id_matricola', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'id_immobile', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'mq_commerciali', 'decimal(15,2) DEFAULT NULL' ),
	( 'valutazioni', 'mq_calpestabili', 'decimal(15,2) DEFAULT NULL' ),
	( 'valutazioni', 'id_condizione', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'id_disponibilita', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'id_classe_energetica', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'note', 'text DEFAULT NULL' ),
	( 'valutazioni', 'timestamp_valutazione', 'int(11) DEFAULT NULL' ),
	( 'valutazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'valutazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'valutazioni_certificazioni', 'id_valutazione', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'id_certificazione', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'id_emittente', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'nome', 'char(1) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'codice', 'char(32) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'data_emissione', 'date DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'data_scadenza', 'date DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'note', 'text DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'valutazioni_certificazioni', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'zone_cap', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'zone_cap', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'zone_cap', 'id_zona', 'bigint(20) DEFAULT NULL' ),
	( 'zone_cap', 'cap', 'char(8) DEFAULT NULL' ),
	( 'zone_cap', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'zone_cap', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'zone_cap', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'zone_cap', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'zone_indirizzi', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'zone_indirizzi', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'zone_indirizzi', 'id_zona', 'bigint(20) DEFAULT NULL' ),
	( 'zone_indirizzi', 'id_indirizzo', 'bigint(20) DEFAULT NULL' ),
	( 'zone_indirizzi', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'zone_indirizzi', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'zone_indirizzi', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'zone_indirizzi', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' ),
	( 'zone_stati', 'id', 'bigint(20) NOT NULL AUTO_INCREMENT' ),
	( 'zone_stati', 'ordine', 'int(11) DEFAULT NULL' ),
	( 'zone_stati', 'id_zona', 'bigint(20) DEFAULT NULL' ),
	( 'zone_stati', 'id_stato', 'bigint(20) DEFAULT NULL' ),
	( 'zone_stati', 'id_account_inserimento', 'bigint(20) DEFAULT NULL' ),
	( 'zone_stati', 'timestamp_inserimento', 'int(11) DEFAULT NULL' ),
	( 'zone_stati', 'id_account_aggiornamento', 'bigint(20) DEFAULT NULL' ),
	( 'zone_stati', 'timestamp_aggiornamento', 'int(11) DEFAULT NULL' );

-- | 202609291853

-- la procedura che aggiunge le colonne mancanti alle tabelle che ci sono, e annota invece di fermare il task
CREATE OR REPLACE PROCEDURE `__patch_colonne_riallineamento__`()
BEGIN

    DECLARE fine INT DEFAULT 0;
    DECLARE v_tabella, v_colonna VARCHAR(64);
    DECLARE v_definizione TEXT;
    DECLARE messaggio TEXT DEFAULT NULL;
    DECLARE mancanti CURSOR FOR
        SELECT p.`tabella`, p.`colonna`, p.`definizione`
        FROM `__patch_colonne_riallineamento__` AS p
        INNER JOIN information_schema.tables AS t
            ON t.table_schema = DATABASE() AND t.table_name = p.`tabella` COLLATE utf8_general_ci AND t.table_type = 'BASE TABLE'
        WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns AS c
            WHERE c.table_schema = DATABASE() AND c.table_name = p.`tabella` COLLATE utf8_general_ci AND c.column_name = p.`colonna` COLLATE utf8_general_ci
        )
        ORDER BY p.`tabella`, p.`colonna`;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET fine = 1;

    OPEN mancanti;
    giro: LOOP

        FETCH mancanti INTO v_tabella, v_colonna, v_definizione;
        IF fine = 1 THEN
            LEAVE giro;
        END IF;

        BEGIN
            DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
                BEGIN
                    GET DIAGNOSTICS CONDITION 1 messaggio = MESSAGE_TEXT;
                END;
            SET messaggio = NULL;
            SET @colonne_riallineamento_sql = CONCAT( 'ALTER TABLE `', v_tabella, '` ADD COLUMN IF NOT EXISTS `', v_colonna, '` ', v_definizione );
            PREPARE aggiunta FROM @colonne_riallineamento_sql;
            IF messaggio IS NULL THEN
                EXECUTE aggiunta;
                DEALLOCATE PREPARE aggiunta;
            END IF;
            SET @colonne_riallineamento_note = CONCAT_WS( '\n', @colonne_riallineamento_note,
                CONCAT( v_tabella, '.', v_colonna, ': ', COALESCE( messaggio, 'aggiunta, vuota' ) ) );
        END;

    END LOOP;
    CLOSE mancanti;

END;

-- | 202609291854

CALL `__patch_colonne_riallineamento__`();

-- | 202609291855

-- le colonne aggiunte e quelle che non si sono potute aggiungere: lo legge chi applica la patch a mano
SELECT @colonne_riallineamento_note AS nota;

-- | 202609291856

-- si liberano procedura e tabella di lavoro
DROP PROCEDURE IF EXISTS `__patch_colonne_riallineamento__`;

-- | 202609291857

DROP TABLE IF EXISTS `__patch_colonne_riallineamento__`;

-- | FINE FILE
