[generic]
scheda_senza_contesto[pt-PT]                    = "este separador precisa de um contexto, selecione um item de"
questa_vista[pt-PT]                             = "esta vista"
per_proseguire[pt-PT]                           = "para continuar"
