[generic]
scheda_senza_contesto[sv-SE]                    = "den här fliken behöver ett sammanhang, välj ett objekt från"
questa_vista[sv-SE]                             = "den här vyn"
per_proseguire[sv-SE]                           = "för att fortsätta"
