[generic]
scheda_senza_contesto[hr-HR]                    = "ova kartica treba kontekst, odaberite stavku iz"
questa_vista[hr-HR]                             = "ovog prikaza"
per_proseguire[hr-HR]                           = "za nastavak"
