[generic]
scheda_senza_contesto[pt-BR]                    = "esta aba precisa de um contexto, selecione um item de"
questa_vista[pt-BR]                             = "esta visualização"
per_proseguire[pt-BR]                           = "para continuar"
