[generic]
cap[en-US]                      = "ZIP code"
scheda_senza_contesto[en-US]                    = "this tab needs a context, select an item from"
questa_vista[en-US]                             = "this view"
per_proseguire[en-US]                           = "to continue"
