[generic]
accetta[es-ES]                = "aceptar"
email[es-ES]                = "correo electrónico"
facoltativo[es-ES]            = "opcional"
invia[es-ES]                = "enviar"
login[es-ES]                = "identificate"
logout[es-ES]                = "cerrar sesión"
nega[es-ES]                    = "rechazar"
nome[es-ES]                    = "nombre"
nome_utente[es-ES]            = "nombre de usuario"
obbligatorio[es-ES]            = "obligatorio"
password[es-ES]                = "contraseña"
privacy_policy_sito[es-ES]    = "la política de privacidad y cookies del sitio"
registrazione[es-ES]        = "registrate"
tua_domanda[es-ES]            = "tu pregunta"
scheda_senza_contesto[es-ES]                    = "esta pestaña necesita un contexto, selecciona un elemento de"
questa_vista[es-ES]                             = "esta vista"
per_proseguire[es-ES]                           = "para continuar"
