[generic]
accetta[ro-RO]                = "accept"
email[ro-RO]                = "e-mail"
facoltativo[ro-RO]            = "opțional"
invia[ro-RO]                = "trimite"
login[ro-RO]                = "autentificare"
logout[ro-RO]                = "deconectare"
nega[ro-RO]                    = "refuz"
nome[ro-RO]                    = "nume"
nome_utente[ro-RO]            = "nume de utilizator"
obbligatorio[ro-RO]            = "obligatoriu"
password[ro-RO]                = "parolă"
privacy_policy_sito[ro-RO]    = "politica de confidențialitate și cookie-uri a site-ului"
registrazione[ro-RO]        = "înregistrare"
tua_domanda[ro-RO]            = "întrebarea ta"
scheda_senza_contesto[ro-RO]                    = "această filă necesită un context, selectează un element din"
questa_vista[ro-RO]                             = "această vizualizare"
per_proseguire[ro-RO]                           = "pentru a continua"
