[generic]
scheda_senza_contesto[ja-JP]                    = "このタブにはコンテキストが必要です。項目を選択してください:"
questa_vista[ja-JP]                             = "このビュー"
per_proseguire[ja-JP]                           = "続行するには"
