[generic]
accetta[cs-CZ]                          = ???
email[cs-CZ]                            = ???
scheda_senza_contesto[cs-CZ]                    = ???
questa_vista[cs-CZ]                             = ???
per_proseguire[cs-CZ]                           = ???
