[generic]
scheda_senza_contesto[hu-HU]                    = "ehhez a laphoz kontextus kell, válasszon egy elemet"
questa_vista[hu-HU]                             = "ebből a nézetből"
per_proseguire[hu-HU]                           = "a folytatáshoz"
