[generic]
accetta[ru-RU]                = "принять"
email[ru-RU]                = "эл. почта"
facoltativo[ru-RU]            = "необязательно"
invia[ru-RU]                = "отправить"
login[ru-RU]                = "вход"
logout[ru-RU]                = "выйти"
nega[ru-RU]                    = "отклонить"
nome[ru-RU]                    = "имя"
nome_utente[ru-RU]            = "имя пользователя"
obbligatorio[ru-RU]            = "обязательно"
password[ru-RU]                = "пароль"
privacy_policy_sito[ru-RU]    = "политика конфиденциальности и использования файлов cookie сайта"
registrazione[ru-RU]        = "регистрация"
tua_domanda[ru-RU]            = "ваш вопрос"
scheda_senza_contesto[ru-RU]                    = "этой вкладке нужен контекст, выберите элемент в"
questa_vista[ru-RU]                             = "этом представлении"
per_proseguire[ru-RU]                           = "чтобы продолжить"
