[generic]
accetta[pl-PL]                = "akceptuję"
email[pl-PL]                = "e-mail"
facoltativo[pl-PL]            = "opcjonalne"
invia[pl-PL]                = "wyślij"
login[pl-PL]                = "zalogować"
logout[pl-PL]                = "wylogować"
nega[pl-PL]                    = "odmawiam"
nome[pl-PL]                    = "imię"
nome_utente[pl-PL]            = "nazwa użytkownika"
obbligatorio[pl-PL]            = "wymagane"
password[pl-PL]                = hasło
privacy_policy_sito[pl-PL]    = "polityka prywatności i plików cookie serwisu"
registrazione[pl-PL]        = "rejestracja"
tua_domanda[pl-PL]            = "twoje pytanie"
scheda_senza_contesto[pl-PL]                    = "ta karta wymaga kontekstu, wybierz element z"
questa_vista[pl-PL]                             = "tego widoku"
per_proseguire[pl-PL]                           = "aby kontynuować"
