[generic]
accetta[de-DE]                          = "akzeptieren"
email[de-DE]                            = "E-Mail"
facoltativo[de-DE]                      = "optional"
invia[de-DE]                            = "senden"
login[de-DE]                            = "einloggen"
logout[de-DE]                           = "Abmelden"
nega[de-DE]                             = "ablehnen"
nome[de-DE]                             = "Name"
nome_utente[de-DE]                      = "Benutzername"
obbligatorio[de-DE]                     = "Pflichtfeld"
password[de-DE]                         = "Passwort"
privacy_policy_sito[de-DE]              = "die Datenschutz- und Cookie-Richtlinie der Website"
registrazione[de-DE]                    = "eintragen"
tua_domanda[de-DE]                      = "Ihre Frage"
scheda_senza_contesto[de-DE]                    = "diese Registerkarte benötigt einen Kontext, wählen Sie ein Element aus"
questa_vista[de-DE]                             = "dieser Ansicht"
per_proseguire[de-DE]                           = "um fortzufahren"
