[generic]
accetta[cs-CZ]                          = "přijmout"
email[cs-CZ]                            = "e-mail"
scheda_senza_contesto[cs-CZ]                    = "tato karta vyžaduje kontext, vyberte položku z"
questa_vista[cs-CZ]                             = "tohoto zobrazení"
per_proseguire[cs-CZ]                           = "pro pokračování"
