INSERT INTO `categorie_anagrafica` (`id`, `id_genitore`, `ordine`, `nome`, `se_lead`, `se_prospect`, `se_cliente`, `se_fornitore`, `se_produttore`, `se_collaboratore`, `se_interno`, `se_esterno`, `se_agente`, `se_concorrente`, `se_azienda_gestita`, `se_amministrazione`, `se_produzione`, `se_notizie`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	NULL,	'clienti',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	NULL,	'collaboratori',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	2,	NULL,	'agenti',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	NULL,	'fornitori',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `se_lead` = VALUES(`se_lead`), `se_prospect` = VALUES(`se_prospect`), `se_cliente` = VALUES(`se_cliente`), `se_fornitore` = VALUES(`se_fornitore`), `se_produttore` = VALUES(`se_produttore`), `se_collaboratore` = VALUES(`se_collaboratore`), `se_interno` = VALUES(`se_interno`), `se_esterno` = VALUES(`se_esterno`), `se_agente` = VALUES(`se_agente`), `se_concorrente` = VALUES(`se_concorrente`), `se_azienda_gestita` = VALUES(`se_azienda_gestita`), `se_amministrazione` = VALUES(`se_amministrazione`), `se_produzione` = VALUES(`se_produzione`), `se_notizie` = VALUES(`se_notizie`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `colori` (`id`, `id_genitore`, `nome`, `hex`, `r`, `g`, `b`, `ral`, `pantone`, `c`, `m`, `y`, `k`) VALUES
(1,	NULL,	'rosso',	'ff0000',	255,	0,	0,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	'bianco',	'ffffff',	255,	255,	255,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	'nero',	'000000',	0,	0,	0,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	NULL,	'blu',	'0000ff',	0,	0,	255,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(6,	NULL,	'verde',	'00ff00',	0,	255,	0,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `hex` = VALUES(`hex`), `r` = VALUES(`r`), `g` = VALUES(`g`), `b` = VALUES(`b`), `ral` = VALUES(`ral`), `pantone` = VALUES(`pantone`), `c` = VALUES(`c`), `m` = VALUES(`m`), `y` = VALUES(`y`), `k` = VALUES(`k`);

INSERT INTO `comuni` (`id`, `id_provincia`, `nome`, `codice_istat`, `codice_catasto`) VALUES
(1,	1,	'Bologna',	'037006',	'A944'),
(2,	1,	'Casalecchio di Reno',	'037011',	'B880'),
(3,	1,	'San Giovanni in Persiceto',	'037053',	'G467'),
(4,	1,	'Crevalcore',	'037024',	'D166'),
(8,	1,	'Monte San Pietro',	'037042',	'F627'),
(9,	1,	'San Lazzaro di Savena',	'037054',	'H945'),
(10,	1,	'Castel Maggiore',	'037019',	'C204'),
(13,	1,	'Zola Predosa',	'037060',	'M185'),
(16,	1,	'Anzola dell\'Emilia',	'037001',	'A324'),
(3980,	1,	'Argelato',	'037002',	'A392'),
(3981,	1,	'Baricella',	'037003',	'A665'),
(3983,	1,	'Bentivoglio',	'037005',	'A785'),
(3984,	1,	'Borgo Tossignano',	'037007',	'B044'),
(3985,	1,	'Budrio',	'037008',	'B249'),
(3986,	1,	'Calderara di Reno',	'037009',	'B399'),
(3987,	1,	'Camugnano',	'037010',	'B572'),
(3988,	1,	'Casalfiumanese',	'037012',	'B892'),
(3989,	1,	'Castel d\'Aiano',	'037013',	'C075'),
(3990,	1,	'Castel del Rio',	'037014',	'C086'),
(3991,	1,	'Castel di Casio',	'037015',	'B969'),
(3992,	1,	'Castel Guelfo di Bologna',	'037016',	'C121'),
(3993,	1,	'Castello d\'Argile',	'037017',	'C185'),
(3995,	1,	'Castel San Pietro Terme',	'037020',	'C265'),
(3996,	1,	'Castenaso',	'037021',	'C292'),
(3997,	1,	'Castiglione dei Pepoli',	'037022',	'C296'),
(3999,	1,	'Dozza',	'037025',	'D360'),
(4000,	1,	'Fontanelice',	'037026',	'D668'),
(4001,	1,	'Gaggio Montano',	'037027',	'D847'),
(4002,	1,	'Galliera',	'037028',	'D878'),
(4004,	1,	'Granarolo dell\'Emilia',	'037030',	'E136'),
(4005,	1,	'Grizzana Morandi',	'037031',	'E187'),
(4006,	1,	'Imola',	'037032',	'E289'),
(4007,	1,	'Lizzano in Belvedere',	'037033',	'A771'),
(4008,	1,	'Loiano',	'037034',	'E655'),
(4009,	1,	'Malalbergo',	'037035',	'E844'),
(4010,	1,	'Marzabotto',	'037036',	'B689'),
(4011,	1,	'Medicina',	'037037',	'F083'),
(4012,	1,	'Minerbio',	'037038',	'F219'),
(4013,	1,	'Molinella',	'037039',	'F288'),
(4014,	1,	'Monghidoro',	'037040',	'F363'),
(4015,	1,	'Monterenzio',	'037041',	'F597'),
(4017,	1,	'Monzuno',	'037044',	'F706'),
(4018,	1,	'Mordano',	'037045',	'F718'),
(4019,	1,	'Ozzano dell\'Emilia',	'037046',	'G205'),
(4020,	1,	'Pianoro',	'037047',	'G570'),
(4021,	1,	'Pieve di Cento',	'037048',	'G643'),
(4023,	1,	'Sala Bolognese',	'037050',	'H678'),
(4024,	1,	'San Benedetto Val di Sambro',	'037051',	'G566'),
(4025,	1,	'San Giorgio di Piano',	'037052',	'H896'),
(4026,	1,	'San Pietro in Casale',	'037055',	'I110'),
(4027,	1,	'Sant\'Agata Bolognese',	'037056',	'I191'),
(4028,	1,	'Sasso Marconi',	'037057',	'G972'),
(4030,	1,	'Vergato',	'037059',	'L762'),
(12594,	1,	'Valsamoggia',	'037061',	'M320'),
(12595,	1,	'Alto Reno Terme',	'037062',	'M369')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_provincia` = VALUES(`id_provincia`), `nome` = VALUES(`nome`), `codice_istat` = VALUES(`codice_istat`), `codice_catasto` = VALUES(`codice_catasto`);

INSERT INTO `continenti` (`id`, `codice`, `nome`) VALUES
(1,	'EU',	'Europa'),
(2,	'AF',	'Africa'),
(3,	'AS',	'Asia'),
(4,	'NA',	'Nord America'),
(5,	'AU',	'Oceania'),
(6,	'LA',	'America Latina'),
(7,	'AN',	'Antartide')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `codice` = VALUES(`codice`), `nome` = VALUES(`nome`);

INSERT INTO `iva` (`id`, `aliquota`, `nome`, `descrizione`, `codice`, `timestamp_archiviazione`) VALUES
(1,	22.00,	'IVA 22%',	'IVA 22%',	NULL,	NULL),
(2,	10.00,	'IVA agevolata 10%',	'IVA agevolata 10%',	NULL,	NULL),
(3,	4.00,	'IVA agevolata 4%',	'IVA agevolata 4%',	NULL,	NULL),
(4,	0.00,	'escluso ex art. 15 d.P.R. n. 633/1972',	'operazione esclusa ex art. 15 del d.P.R. n. 633/1972',	'N1',	NULL),
(5,	0.00,	'non soggetto ex art.7 d.P.R. 633/1972',	'operazione non soggetta a IVA ex art. 7 del d.P.R. 633/1972',	'N2',	NULL),
(6,	0.00,	'non imponibile ex art. 8 d.P.R. 633/1972',	'operazione non imponibile ex art. 8 del d.P.R. 633/1972',	'N3',	NULL),
(7,	0.00,	'fuori campo IVA ex art. 2 d.P.R. 633/1972',	'operazione non imponibile ex art. 2 del d.P.R. 633/1972',	'N2',	NULL),
(8,	0.00,	'non soggetto ex art. 1 ll. nn. 190/2014, 208/2015 e 145/2018',	'operazione non soggetta a IVA ai sensi ex art. 1 legge 190/2014 come modificato dalla legge n. 208/2015 e dalla legge n. 145/2018',	'N2',	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `aliquota` = VALUES(`aliquota`), `nome` = VALUES(`nome`), `descrizione` = VALUES(`descrizione`), `codice` = VALUES(`codice`), `timestamp_archiviazione` = VALUES(`timestamp_archiviazione`);

INSERT INTO `lingue` (`id`, `nome`, `note`, `iso6391alpha2`, `iso6393alpha3`, `ietf`) VALUES
(1,	'italiano',	'italiano (Italia)',	'it',	'ita',	'it-IT'),
(2,	'ceco',	'ceco (Repubblica Ceca)',	'cs',	'ces',	'cs-CZ'),
(3,	'inglese',	'inglese (Regno Unito)',	'en',	'eng',	'en-GB'),
(4,	'francese',	'francese (Francia)',	'fr',	'fra',	'fr-FR'),
(5,	'tedesco',	'tedesco (Germania)',	'de',	'deu',	'de-DE'),
(6,	'ungherese',	'ungherese (Ungheria)',	'hu',	'hun',	'hu-HU'),
(7,	'giapponese',	'giapponese (Giappone)',	'ja',	'jpn',	'ja-JP'),
(8,	'polacco',	'polacco (Polonia)',	'pl',	'pol',	'pl-PL'),
(9,	'portoghese',	'portoghese (Portogallo)',	'pt',	'por',	'pt-PT'),
(10,	'russo',	'russo (Russia)',	'ru',	'rus',	'ru-RU'),
(11,	'spagnolo',	'spagnolo (Spagna)',	'es',	'spa',	'es-ES'),
(12,	'svedese',	'svedese (Svezia)',	'sv',	'swe',	'sv-SE'),
(13,	'americano',	'inglese (Stati Uniti)',	NULL,	NULL,	'en-US'),
(14,	'croato',	'croato (Croazia)',	'hr',	'hrv',	'hr-HR'),
(15,	'rumeno',	'rumeno (Romania)',	'ro',	'ron',	'ro-RO')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `nome` = VALUES(`nome`), `note` = VALUES(`note`), `iso6391alpha2` = VALUES(`iso6391alpha2`), `iso6393alpha3` = VALUES(`iso6393alpha3`), `ietf` = VALUES(`ietf`);

INSERT INTO `periodicita` (`id`, `nome`) VALUES
(4,	'annuale'),
(1,	'giornaliera'),
(3,	'mensile'),
(2,	'settimanale')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `nome` = VALUES(`nome`);

INSERT INTO `provincie` (`id`, `id_regione`, `nome`, `sigla`, `codice_istat`) VALUES
(1,	1,	'Bologna',	'BO',	'237'),
(2,	1,	'Modena',	'MO',	'036'),
(3,	1,	'Forlì-Cesena',	'FC',	'040'),
(4,	1,	'Ravenna',	'RA',	'039'),
(5,	2,	'Ancona',	'AN',	'042'),
(6,	2,	'Ascoli Piceno',	'AP',	'044'),
(7,	20,	'Palermo',	'PA',	'282'),
(8,	4,	'Brescia',	'BS',	'017'),
(9,	5,	'Torino',	'TO',	'201'),
(10,	5,	'Vercelli',	'VC',	'002'),
(11,	5,	'Novara',	'NO',	'003'),
(12,	5,	'Cuneo',	'CN',	'004'),
(13,	5,	'Asti',	'AT',	'005'),
(14,	5,	'Alessandria',	'AL',	'006'),
(15,	5,	'Biella',	'BI',	'096'),
(16,	5,	'Verbano-Cusio-Ossola',	'VB',	'103'),
(17,	6,	'Valle d\'Aosta/Vallée d\'Aoste',	'AO',	'007'),
(18,	4,	'Varese',	'VA',	'012'),
(19,	4,	'Como',	'CO',	'013'),
(20,	4,	'Sondrio',	'SO',	'014'),
(21,	4,	'Milano',	'MI',	'215'),
(22,	4,	'Bergamo',	'BG',	'016'),
(23,	4,	'Pavia',	'PV',	'018'),
(24,	4,	'Cremona',	'CR',	'019'),
(25,	4,	'Mantova',	'MN',	'020'),
(26,	4,	'Lecco',	'LC',	'097'),
(27,	4,	'Lodi',	'LO',	'098'),
(28,	4,	'Monza e della Brianza',	'MB',	'108'),
(29,	7,	'Bolzano/Bozen',	'BZ',	'021'),
(30,	7,	'Trento',	'TN',	'022'),
(31,	8,	'Verona',	'VR',	'023'),
(32,	8,	'Vicenza',	'VI',	'024'),
(33,	8,	'Belluno',	'BL',	'025'),
(34,	8,	'Treviso',	'TV',	'026'),
(35,	8,	'Venezia',	'VE',	'227'),
(36,	8,	'Padova',	'PD',	'028'),
(37,	8,	'Rovigo',	'RO',	'029'),
(38,	9,	'Udine',	'UD',	'030'),
(39,	9,	'Gorizia',	'GO',	'031'),
(40,	9,	'Trieste',	'TS',	'032'),
(41,	9,	'Pordenone',	'PN',	'093'),
(42,	10,	'Imperia',	'IM',	'008'),
(43,	10,	'Savona',	'SV',	'009'),
(44,	10,	'Genova',	'GE',	'210'),
(45,	10,	'La Spezia',	'SP',	'011'),
(46,	1,	'Piacenza',	'PC',	'033'),
(47,	1,	'Parma',	'PR',	'034'),
(48,	1,	'Reggio nell\'Emilia',	'RE',	'035'),
(49,	1,	'Ferrara',	'FE',	'038'),
(51,	1,	'Rimini',	'RN',	'099'),
(52,	11,	'Massa-Carrara',	'MS',	'045'),
(53,	11,	'Lucca',	'LU',	'046'),
(54,	11,	'Pistoia',	'PT',	'047'),
(55,	11,	'Firenze',	'FI',	'248'),
(56,	11,	'Livorno',	'LI',	'049'),
(57,	11,	'Pisa',	'PI',	'050'),
(58,	11,	'Arezzo',	'AR',	'051'),
(59,	11,	'Siena',	'SI',	'052'),
(60,	11,	'Grosseto',	'GR',	'053'),
(61,	11,	'Prato',	'PO',	'100'),
(62,	12,	'Perugia',	'PG',	'054'),
(63,	12,	'Terni',	'TR',	'055'),
(64,	2,	'Pesaro e Urbino',	'PU',	'041'),
(65,	2,	'Macerata',	'MC',	'043'),
(66,	2,	'Fermo',	'FM',	'109'),
(67,	13,	'Viterbo',	'VT',	'056'),
(68,	13,	'Rieti',	'RI',	'057'),
(69,	13,	'Roma',	'RM',	'258'),
(70,	13,	'Latina',	'LT',	'059'),
(71,	13,	'Frosinone',	'FR',	'060'),
(72,	14,	'L\'Aquila',	'AQ',	'066'),
(73,	14,	'Teramo',	'TE',	'067'),
(74,	14,	'Pescara',	'PE',	'068'),
(75,	14,	'Chieti',	'CH',	'069'),
(76,	15,	'Campobasso',	'CB',	'070'),
(77,	15,	'Isernia',	'IS',	'094'),
(78,	16,	'Caserta',	'CE',	'061'),
(79,	16,	'Benevento',	'BN',	'062'),
(80,	16,	'Napoli',	'NA',	'263'),
(81,	16,	'Avellino',	'AV',	'064'),
(82,	16,	'Salerno',	'SA',	'065'),
(83,	17,	'Foggia',	'FG',	'071'),
(84,	17,	'Bari',	'BA',	'272'),
(85,	17,	'Taranto',	'TA',	'073'),
(86,	17,	'Brindisi',	'BR',	'074'),
(87,	17,	'Lecce',	'LE',	'075'),
(88,	17,	'Barletta-Andria-Trani',	'BT',	'110'),
(89,	18,	'Potenza',	'PZ',	'076'),
(90,	18,	'Matera',	'MT',	'077'),
(91,	19,	'Cosenza',	'CS',	'078'),
(92,	19,	'Catanzaro',	'CZ',	'079'),
(93,	19,	'Reggio Calabria',	'RC',	'280'),
(94,	19,	'Crotone',	'KR',	'101'),
(95,	19,	'Vibo Valentia',	'VV',	'102'),
(96,	20,	'Trapani',	'TP',	'081'),
(98,	20,	'Messina',	'ME',	'283'),
(99,	20,	'Agrigento',	'AG',	'084'),
(100,	20,	'Caltanissetta',	'CL',	'085'),
(101,	20,	'Enna',	'EN',	'086'),
(102,	20,	'Catania',	'CT',	'287'),
(103,	20,	'Ragusa',	'RG',	'088'),
(104,	20,	'Siracusa',	'SR',	'089'),
(105,	21,	'Sassari',	'SS',	'090'),
(106,	21,	'Nuoro',	'NU',	'091'),
(107,	21,	'Cagliari',	'CA',	'292'),
(108,	21,	'Oristano',	'OR',	'095'),
(109,	21,	'Olbia-Tempio',	'OT',	NULL),
(110,	21,	'Ogliastra',	'OG',	NULL),
(111,	21,	'Sud Sardegna',	'SU',	'111')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_regione` = VALUES(`id_regione`), `nome` = VALUES(`nome`), `sigla` = VALUES(`sigla`), `codice_istat` = VALUES(`codice_istat`);

INSERT INTO `ranking` (`id`, `nome`, `ordine`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	'GOLD',	100,	NULL,	NULL,	NULL,	NULL),
(2,	'SILVER',	200,	NULL,	NULL,	NULL,	NULL),
(3,	'BRONZE',	300,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `nome` = VALUES(`nome`), `ordine` = VALUES(`ordine`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `regimi` (`id`, `nome`, `codice`) VALUES
(1,	'privato',	NULL),
(2,	'ordinario',	'RF01'),
(3,	'minimi',	'RF02'),
(4,	'agricoltura e pesca',	'RF04'),
(5,	'sali e tabacchi',	'RF05'),
(6,	'editoria',	'RF07'),
(7,	'intrattenimento',	'RF10'),
(8,	'viaggi e turismo',	'RF11'),
(9,	'agriturismo',	'RF12'),
(10,	'vendite a domicilio',	'RF13'),
(11,	'beni usati e collezionismo',	'RF14'),
(12,	'IVA per cassa P.A.',	'RF16'),
(13,	'IVA per cassa',	'RF17'),
(14,	'altro',	'RF18'),
(15,	'forfettario',	'RF19')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `nome` = VALUES(`nome`), `codice` = VALUES(`codice`);

INSERT INTO `regioni` (`id`, `id_stato`, `nome`, `codice_istat`) VALUES
(1,	1,	'Emilia-Romagna',	'08'),
(2,	1,	'Marche',	'11'),
(4,	1,	'Lombardia',	'03'),
(5,	1,	'Piemonte',	'01'),
(6,	1,	'Valle d\'Aosta/Vallée d\'Aoste',	'02'),
(7,	1,	'Trentino-Alto Adige/Südtirol',	'04'),
(8,	1,	'Veneto',	'05'),
(9,	1,	'Friuli-Venezia Giulia',	'06'),
(10,	1,	'Liguria',	'07'),
(11,	1,	'Toscana',	'09'),
(12,	1,	'Umbria',	'10'),
(13,	1,	'Lazio',	'12'),
(14,	1,	'Abruzzo',	'13'),
(15,	1,	'Molise',	'14'),
(16,	1,	'Campania',	'15'),
(17,	1,	'Puglia',	'16'),
(18,	1,	'Basilicata',	'17'),
(19,	1,	'Calabria',	'18'),
(20,	1,	'Sicilia',	'19'),
(21,	1,	'Sardegna',	'20')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_stato` = VALUES(`id_stato`), `nome` = VALUES(`nome`), `codice_istat` = VALUES(`codice_istat`);

INSERT INTO `ruoli_anagrafica` (`id`, `id_genitore`, `nome`, `html_entity`, `font_awesome`, `se_organizzazioni`, `se_risorse`, `se_progetti`) VALUES
(1,	NULL,	'titolare',	NULL,	NULL,	1,	NULL,	NULL),
(2,	NULL,	'amministratore',	NULL,	NULL,	1,	NULL,	NULL),
(3,	NULL,	'socio',	NULL,	NULL,	1,	NULL,	NULL),
(4,	NULL,	'dipendente',	NULL,	NULL,	1,	NULL,	NULL),
(5,	NULL,	'direttore',	NULL,	NULL,	1,	NULL,	NULL),
(6,	NULL,	'presidente',	NULL,	NULL,	1,	NULL,	NULL),
(7,	NULL,	'tesoriere',	NULL,	NULL,	1,	NULL,	NULL),
(8,	NULL,	'coordinatore',	NULL,	NULL,	1,	NULL,	1),
(9,	NULL,	'vicepresidente',	NULL,	NULL,	1,	NULL,	NULL),
(10,	NULL,	'vicedirettore',	NULL,	NULL,	1,	NULL,	NULL),
(11,	NULL,	'segretario',	NULL,	NULL,	1,	NULL,	NULL),
(12,	NULL,	'responsabile amministrativo',	NULL,	NULL,	1,	NULL,	NULL),
(13,	NULL,	'responsabile acquisti',	NULL,	NULL,	1,	NULL,	NULL),
(14,	NULL,	'responsabile operativo',	NULL,	NULL,	1,	NULL,	NULL),
(15,	NULL,	'operatore',	NULL,	NULL,	NULL,	NULL,	1),
(16,	NULL,	'responsabile',	NULL,	NULL,	NULL,	NULL,	1),
(17,	NULL,	'assistente',	NULL,	NULL,	1,	NULL,	1),
(18,	NULL,	'autore',	NULL,	NULL,	NULL,	1,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_organizzazioni` = VALUES(`se_organizzazioni`), `se_risorse` = VALUES(`se_risorse`), `se_progetti` = VALUES(`se_progetti`);

INSERT INTO `ruoli_audio` (`id`, `id_genitore`, `nome`, `html_entity`, `font_awesome`, `se_anagrafica`, `se_pagine`, `se_prodotti`, `se_articoli`, `se_categorie_prodotti`, `se_notizie`, `se_categorie_notizie`, `se_risorse`, `se_categorie_risorse`) VALUES
(1,	NULL,	'audio',	NULL,	NULL,	1,	1,	1,	1,	1,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	'commento',	NULL,	NULL,	NULL,	1,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_anagrafica` = VALUES(`se_anagrafica`), `se_pagine` = VALUES(`se_pagine`), `se_prodotti` = VALUES(`se_prodotti`), `se_articoli` = VALUES(`se_articoli`), `se_categorie_prodotti` = VALUES(`se_categorie_prodotti`), `se_notizie` = VALUES(`se_notizie`), `se_categorie_notizie` = VALUES(`se_categorie_notizie`), `se_risorse` = VALUES(`se_risorse`), `se_categorie_risorse` = VALUES(`se_categorie_risorse`);

INSERT INTO `ruoli_file` (`id`, `id_genitore`, `nome`, `html_entity`, `font_awesome`, `se_anagrafica`, `se_pagine`, `se_template`, `se_prodotti`, `se_articoli`, `se_categorie_prodotti`, `se_notizie`, `se_categorie_notizie`, `se_risorse`, `se_categorie_risorse`) VALUES
(1,	NULL,	'allegato',	NULL,	NULL,	1,	1,	1,	1,	1,	1,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	'brochure',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	'documentazione',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	'driver',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	NULL,	'manualistica',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL),
(6,	NULL,	'press kit',	NULL,	NULL,	1,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(7,	NULL,	'schede tecniche',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL),
(8,	NULL,	'software',	NULL,	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_anagrafica` = VALUES(`se_anagrafica`), `se_pagine` = VALUES(`se_pagine`), `se_template` = VALUES(`se_template`), `se_prodotti` = VALUES(`se_prodotti`), `se_articoli` = VALUES(`se_articoli`), `se_categorie_prodotti` = VALUES(`se_categorie_prodotti`), `se_notizie` = VALUES(`se_notizie`), `se_categorie_notizie` = VALUES(`se_categorie_notizie`), `se_risorse` = VALUES(`se_risorse`), `se_categorie_risorse` = VALUES(`se_categorie_risorse`);

INSERT INTO `ruoli_immagini` (`id`, `id_genitore`, `ordine_scalamento`, `nome`, `html_entity`, `font_awesome`, `se_anagrafica`, `se_pagine`, `se_prodotti`, `se_articoli`, `se_categorie_prodotti`, `se_notizie`, `se_categorie_notizie`, `se_risorse`, `se_categorie_risorse`) VALUES
(1,	NULL,	900,	'immagine',	NULL,	NULL,	1,	1,	1,	1,	1,	1,	1,	1,	1),
(2,	NULL,	300,	'intestazione',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	900,	'sfondo',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	600,	'gallery',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	NULL,	600,	'jumbotron',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	1,	NULL,	1,	NULL,	1),
(6,	NULL,	100,	'avatar',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(7,	NULL,	300,	'logo',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(8,	NULL,	200,	'carousel',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	1,	NULL,	1,	NULL,	1)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine_scalamento` = VALUES(`ordine_scalamento`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_anagrafica` = VALUES(`se_anagrafica`), `se_pagine` = VALUES(`se_pagine`), `se_prodotti` = VALUES(`se_prodotti`), `se_articoli` = VALUES(`se_articoli`), `se_categorie_prodotti` = VALUES(`se_categorie_prodotti`), `se_notizie` = VALUES(`se_notizie`), `se_categorie_notizie` = VALUES(`se_categorie_notizie`), `se_risorse` = VALUES(`se_risorse`), `se_categorie_risorse` = VALUES(`se_categorie_risorse`);

INSERT INTO `ruoli_indirizzi` (`id`, `id_genitore`, `nome`, `html_entity`, `font_awesome`, `se_sede_legale`, `se_sede_operativa`, `se_residenza`, `se_domicilio`) VALUES
(1,	NULL,	'sede legale',	'&#xf1ad;',	'',	1,	NULL,	NULL,	NULL),
(2,	NULL,	'sede operativa',	'&#xf275;',	'',	NULL,	1,	NULL,	NULL),
(3,	NULL,	'casa',	'&#xf015;',	'',	NULL,	NULL,	1,	NULL),
(4,	NULL,	'residenza',	'&#xf015;',	'',	NULL,	NULL,	1,	NULL),
(5,	NULL,	'domicilio',	'&#xf015;',	'',	NULL,	NULL,	1,	1)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_sede_legale` = VALUES(`se_sede_legale`), `se_sede_operativa` = VALUES(`se_sede_operativa`), `se_residenza` = VALUES(`se_residenza`), `se_domicilio` = VALUES(`se_domicilio`);

INSERT INTO `ruoli_prodotti` (`id`, `id_genitore`, `nome`, `html_entity`, `font_awesome`) VALUES
(1,	NULL,	'prodotto',	NULL,	NULL),
(2,	NULL,	'principale',	NULL,	NULL),
(3,	NULL,	'suggerito',	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`);

INSERT INTO `ruoli_video` (`id`, `id_genitore`, `nome`, `html_entity`, `font_awesome`, `se_anagrafica`, `se_pagine`, `se_prodotti`, `se_articoli`, `se_categorie_prodotti`, `se_notizie`, `se_categorie_notizie`, `se_risorse`, `se_categorie_risorse`) VALUES
(1,	NULL,	'intestazione',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	'sfondo',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	'card',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	NULL,	'media',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(7,	NULL,	'gallery',	NULL,	NULL,	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL,	NULL),
(8,	NULL,	'footer',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(9,	NULL,	'contenuto',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(10,	NULL,	'copertina',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(11,	NULL,	'principale',	NULL,	NULL,	NULL,	1,	1,	1,	1,	NULL,	NULL,	NULL,	NULL),
(12,	NULL,	'carousel',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(13,	NULL,	'video',	NULL,	NULL,	1,	1,	1,	1,	1,	NULL,	NULL,	NULL,	NULL),
(14,	NULL,	'jumbotron',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(15,	NULL,	'dettaglio',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(16,	NULL,	'anteprima',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_anagrafica` = VALUES(`se_anagrafica`), `se_pagine` = VALUES(`se_pagine`), `se_prodotti` = VALUES(`se_prodotti`), `se_articoli` = VALUES(`se_articoli`), `se_categorie_prodotti` = VALUES(`se_categorie_prodotti`), `se_notizie` = VALUES(`se_notizie`), `se_categorie_notizie` = VALUES(`se_categorie_notizie`), `se_risorse` = VALUES(`se_risorse`), `se_categorie_risorse` = VALUES(`se_categorie_risorse`);

INSERT INTO `settori` (`id`, `id_genitore`, `nome`, `soprannome`, `ateco`) VALUES
(1,	NULL,	'AGRICOLTURA, SILVICOLTURA E PESCA',	'agricoltura, silvicoltura e pesca',	'A'),
(2,	1,	'COLTIVAZIONI AGRICOLE E PRODUZIONE DI PRODOTTI ANIMALI, CACCIA E SERVIZI CONNESSI',	'coltivazioni, prodotti animali e caccia',	'01'),
(3,	2,	'COLTIVAZIONE DI COLTURE AGRICOLE NON PERMANENTI',	'colture non permanenti',	'01.1'),
(4,	2,	'Coltivazione di cereali (escluso il riso), legumi da granella e semi oleosi',	'coltivazione di cereali, legumi e semi',	'01.11'),
(5,	4,	'Coltivazione di cereali (escluso il riso)',	'coltivazione di cereali',	'01.11.1')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `nome` = VALUES(`nome`), `soprannome` = VALUES(`soprannome`), `ateco` = VALUES(`ateco`);

INSERT INTO `stati` (`id`, `id_continente`, `nome`, `note`, `iso31661alpha2`, `iso31661alpha3`, `codice_istat`, `data_archiviazione`) VALUES
(1,	1,	'Italia',	'Repubblica Italiana',	'IT',	'ITA',	NULL,	NULL),
(2,	1,	'Repubblica Ceca',	NULL,	'CZ',	'CZE',	NULL,	NULL),
(3,	1,	'Ungheria',	NULL,	'HU',	'HUN',	NULL,	NULL),
(4,	3,	'Giappone',	NULL,	'JP',	'JP',	NULL,	NULL),
(6,	1,	'Portogallo',	'Repubblica Portoghese',	'PT',	'PRT',	NULL,	NULL),
(7,	1,	'Russia',	'Federazione Russa',	'RU',	'RUS',	NULL,	NULL),
(8,	1,	'Germania',	'Repubblica Federale di Germania',	'DE',	'DEU',	NULL,	NULL),
(9,	1,	'Regno Unito',	'Regno Unito di Gran Bretagna e Irlanda del Nord',	'GB',	'GBR',	NULL,	NULL),
(10,	4,	'Stati Uniti d\'America',	NULL,	'US',	'USA',	NULL,	NULL),
(12,	1,	'Francia',	'Repubblica Francese',	'FR',	'FRA',	NULL,	NULL),
(13,	1,	'Svezia',	'Regno di Svezia',	'SE',	'SWE',	NULL,	NULL),
(15,	1,	'Albania',	'Repubblica d\'Albania',	'AL',	'ALB',	NULL,	NULL),
(16,	2,	'Angola',	'Repubblica dell\'Angola',	'AO',	'AGO',	NULL,	NULL),
(17,	4,	'Antigua e Barbuda',	'Antigua e Barbuda',	'AG',	'ATG',	NULL,	NULL),
(18,	3,	'Arabia Saudita',	'Regno dell\'Arabia Saudita',	'SA',	'SAU',	NULL,	NULL),
(19,	3,	'Armenia',	'Repubblica di Armenia',	'AM',	'ARM',	NULL,	NULL),
(20,	5,	'Australia',	'Australia',	'AU',	'AUS',	NULL,	NULL),
(21,	1,	'Austria',	'Repubblica d\'Austria',	'AT',	'AUT',	NULL,	NULL),
(22,	3,	'Azerbaigian',	'Repubblica dell\'Azerbaigian',	'AZ',	'AZE',	NULL,	NULL),
(23,	6,	'Bahamas',	'Commonwealth delle Bahamas',	'BS',	'BHS',	NULL,	NULL),
(24,	3,	'Bahrein',	'Regno del Bahrein',	'BH',	'BHR',	NULL,	NULL),
(25,	1,	'Baleari (isole)',	'isole Baleari',	'IB',	'',	NULL,	NULL),
(26,	3,	'Bangladesh',	'Repubblica Popolare del Bangladesh',	'BD',	'BGD',	NULL,	NULL),
(27,	4,	'Barbados',	'Barbados',	'BB',	'BRB',	NULL,	NULL),
(28,	1,	'Belgio',	'Regno del Belgio',	'BE',	'BEL',	NULL,	NULL),
(29,	4,	'Belize',	'Belize',	'BZ',	'BLZ',	NULL,	NULL),
(30,	2,	'Benin',	'Repubblica del Benin',	'BJ',	'BEN',	NULL,	NULL),
(31,	4,	'Bermuda',	'Bermuda',	'BM',	'BMU',	NULL,	NULL),
(32,	1,	'Bielorussia',	'Repubblica di Bielorussia',	'BY',	'BLR',	NULL,	NULL),
(33,	1,	'Bosnia ed Erzegovina',	'Bosnia ed Erzegovina',	'BA',	'BIH',	NULL,	NULL),
(34,	3,	'Brunei',	'Stato del Brunei',	'BN',	'BRN',	NULL,	NULL),
(35,	1,	'Bulgaria',	'Repubblica di Bulgaria',	'BG',	'BG3',	NULL,	NULL),
(36,	2,	'Burkina Faso',	'Burkina Faso',	'BF',	'BFA',	NULL,	NULL),
(37,	2,	'Burundi',	'Repubblica del Burundi',	'BI',	'BDI',	NULL,	NULL),
(38,	3,	'Cambogia',	'Regno di Cambogia',	'KH',	'KHM',	NULL,	NULL),
(39,	4,	'Canada',	'Canada',	'CA',	'CAN',	NULL,	NULL),
(41,	2,	'Capo Verde',	'Repubblica di Capo Verde',	'CV',	'CPV',	NULL,	NULL),
(42,	2,	'Ciad',	'Repubblica del Ciad',	'TD',	'TCD',	NULL,	NULL),
(43,	3,	'Cina',	'Repubblica Popolare Cinese',	'CN',	'CHN',	NULL,	NULL),
(44,	3,	'Cipro',	'Repubblica di Cipro',	'CY',	'CYP',	NULL,	NULL),
(45,	2,	'Comore',	'Unione delle Comore',	'KM',	'COM',	NULL,	NULL),
(46,	3,	'Corea del Nord',	'Repubblica Popolare Democratica di Corea',	'KP',	'PRK',	NULL,	NULL),
(47,	3,	'Corea del Sud',	'Repubblica di Corea',	'KR',	'KOR',	NULL,	NULL),
(48,	2,	'Costa d\'Avorio',	'Repubblica della Costa d\'Avorio',	'CI',	'CIV',	NULL,	NULL),
(49,	1,	'Croazia',	'Repubblica di Croazia',	'HR',	'HRV',	NULL,	NULL),
(50,	1,	'Danimarca',	'Regno di Danimarca',	'DK',	'DNK',	NULL,	NULL),
(51,	2,	'Egitto',	'Repubblica Araba d\'Egitto',	'EG',	'EGY',	NULL,	NULL),
(52,	3,	'Emirati Arabi Uniti',	'Stato degli Emirati Arabi Uniti',	'AE',	'ARE',	NULL,	NULL),
(53,	1,	'Estonia',	'Repubblica d\'Estonia',	'EE',	'EST',	NULL,	NULL),
(54,	3,	'Filippine',	'Repubblica delle Filippine',	'PH',	'PHL',	NULL,	NULL),
(55,	1,	'Finlandia',	'Repubblica di Finlandia',	'FI',	'FIN',	NULL,	NULL),
(56,	2,	'Gabon',	'Repubblica Gabonese',	'GA',	'GAB',	NULL,	NULL),
(57,	2,	'Gambia',	'Repubblica del Gambia',	'GM',	'GMB',	NULL,	NULL),
(58,	4,	'Giamaica',	'Giamaica',	'JM',	'JAM',	NULL,	NULL),
(59,	2,	'Gibuti',	'Repubblica di Gibuti',	'DJ',	'DJI',	NULL,	NULL),
(60,	3,	'Giordania',	'Regno Hascemita di Giordania',	'JO',	'JOR',	NULL,	NULL),
(61,	1,	'Grecia',	'Repubblica Ellenica',	'GR',	'GRC',	NULL,	NULL),
(62,	4,	'Grenada',	'Grenada',	'GD',	'GRD',	NULL,	NULL),
(63,	2,	'Guinea-Bissau',	'Repubblica di Guinea-Bissau',	'GW',	'GNB',	NULL,	NULL),
(64,	4,	'Haiti',	'Repubblica di Haiti',	'HT',	'HTI',	NULL,	NULL),
(65,	3,	'Hong Kong',	'Regione amministrativa speciale di Hong Kong della Repubblica Popolare Cinese',	'HK',	'HKG',	NULL,	NULL),
(66,	3,	'India',	'Repubblica dell\'India',	'IN',	'IND',	NULL,	NULL),
(67,	3,	'Indonesia',	'Repubblica d\'Indonesia',	'ID',	'IDN',	NULL,	NULL),
(68,	1,	'Irlanda',	'Repubblica d\'Irlanda',	'IE',	'IRL',	NULL,	NULL),
(69,	1,	'Islanda',	'Repubblica d\'Islanda',	'IS',	'ISL',	NULL,	NULL),
(70,	4,	'Isole Cayman',	'Isole Cayman',	'KY',	'CYM',	NULL,	NULL),
(71,	3,	'Israele',	'Stato d\'Israele',	'IL',	'ISR',	NULL,	NULL),
(72,	3,	'Kazakistan',	'Repubblica del Kazakistan',	'KZ',	'KAZ',	NULL,	NULL),
(73,	3,	'Kirghizistan',	'Repubblica del Kirghizistan',	'KG',	'KGZ',	NULL,	NULL),
(74,	5,	'Kiribati',	'Repubblica delle Kiribati',	'KI',	'KIR',	NULL,	NULL),
(76,	3,	'Laos',	'Repubblica Popolare Democratica del Laos',	'LA',	'LAO',	NULL,	NULL),
(77,	4,	'Lesotho',	'Regno del Lesotho',	'LS',	'LSO',	NULL,	NULL),
(78,	1,	'Lettonia',	'Repubblica di Lettonia',	'LV',	'LVA',	NULL,	NULL),
(79,	2,	'Liberia',	'Repubblica della Liberia',	'LR',	'LBR',	NULL,	NULL),
(80,	1,	'Liechtenstein',	'Principato del Liechtenstein',	'LI',	'LIE',	NULL,	NULL),
(81,	1,	'Lituania',	'Repubblica di Lituania',	'LT',	'LTU',	NULL,	NULL),
(82,	1,	'Lussemburgo',	'Granducato di Lussemburgo',	'LU',	'LUX',	NULL,	NULL),
(83,	3,	'Macao',	'Regione Amministrativa Speciale di Macao della Repubblica Popolare Cinese',	'MO',	'MAC',	NULL,	NULL),
(84,	1,	'Macedonia del Nord',	'Repubblica della Macedonia del Nord[',	'MK',	'MKD',	NULL,	NULL),
(85,	4,	'Madagascar',	'Repubblica del Madagascar',	'MG',	'MDG',	NULL,	NULL),
(86,	4,	'Malawi',	'Repubblica di Malawi',	'MW',	'MWI',	NULL,	NULL),
(87,	3,	'Maldive',	'Repubblica delle Maldive',	'MV',	'MDV',	NULL,	NULL),
(88,	3,	'Malaysia',	'Malaysia',	'MY',	'MYS',	NULL,	NULL),
(89,	2,	'Mali',	'Repubblica del Mali',	'ML',	'MLI',	NULL,	NULL),
(90,	1,	'Malta',	'Repubblica di Malta',	'MT',	'MLT',	NULL,	NULL),
(91,	2,	'Mauritania',	'Repubblica Islamica della Mauritania',	'MR',	'MRT',	NULL,	NULL),
(92,	2,	'Mauritius',	'Repubblica di Mauritius',	'MU',	'MUS',	NULL,	NULL),
(93,	4,	'Messico',	'Stati Uniti Messicani',	'MX',	'MEX',	NULL,	NULL),
(94,	1,	'Moldavia',	'Repubblica di Moldavia',	'MD',	'MDA',	NULL,	NULL),
(95,	1,	'Monaco',	'Principato di Monaco',	'MC',	'MCO',	NULL,	NULL),
(96,	3,	'Mongolia',	'Mongolia',	'MN',	'MNG',	NULL,	NULL),
(97,	2,	'Namibia',	'Repubblica della Namibia',	'NA',	'NAM',	NULL,	NULL),
(98,	1,	'Norvegia',	'Regno di Norvegia',	'NO',	'NOR',	NULL,	NULL),
(99,	5,	'Nuova Zelanda',	'Nuova Zelanda',	'NZ',	'NZL',	NULL,	NULL),
(101,	1,	'Paesi Bassi',	'Paesi Bassi',	'NL',	'NLD',	NULL,	NULL),
(102,	3,	'Pakistan',	'Repubblica Islamica del Pakistan',	'PK',	'PAK',	NULL,	NULL),
(103,	3,	'Palestina',	'Palestina',	'PS',	'PSE',	NULL,	NULL),
(104,	4,	'Panama',	'Repubblica di Panama',	'PA',	'PAN',	NULL,	NULL),
(105,	5,	'Papua Nuova Guinea',	'Stato Indipendente della Papua Nuova Guinea',	'PG',	'PNG',	NULL,	NULL),
(106,	1,	'Polonia',	'Repubblica di Polonia',	'PL',	'POL',	NULL,	NULL),
(107,	4,	'Porto Rico',	'Stato libero associato di Porto Rico',	'PR',	'PRI',	NULL,	NULL),
(108,	3,	'Qatar',	'Stato del Qatar',	'QA',	'QAT',	NULL,	NULL),
(110,	1,	'Romania',	'Romania',	'RO',	'ROU',	NULL,	NULL),
(111,	4,	'Saint Kitts e Nevis',	'Federazione di Saint Kitts e Nevis',	'KN',	'KNA',	NULL,	NULL),
(112,	4,	'Saint Lucia',	'Saint Lucia',	'LC',	'LCA',	NULL,	NULL),
(114,	2,	'São Tomé e Príncipe',	'Repubblica Democratica di São Tomé e Príncipe',	'ST',	'STP',	NULL,	NULL),
(115,	2,	'Seychelles',	'Repubblica delle Seychelles',	'SC',	'SYC',	NULL,	NULL),
(116,	2,	'Marocco',	NULL,	'MA',	'MAR',	NULL,	NULL),
(117,	3,	'Afghanistan',	'Repubblica Islamica dell\'Afghanistan',	'AF',	'AFG',	NULL,	NULL),
(118,	2,	'Algeria',	'Repubblica Popolare Democratica Algerina',	'DZ',	'DZA',	NULL,	NULL),
(119,	1,	'Andorra',	'Principato di Andorra',	'AD',	'AND',	NULL,	NULL),
(120,	6,	'Argentina',	'Repubblica Argentina',	'AR',	'ARG',	NULL,	NULL),
(121,	2,	'Bhutan',	'Regno del Bhutan',	'BT',	'BTN',	NULL,	NULL),
(122,	3,	'Birmania',	'Unione di Myanmar',	'MM',	'MMR',	NULL,	NULL),
(123,	4,	'Bolivia',	'Stato Plurinazionale di Bolivia',	'BO',	'BOL',	NULL,	NULL),
(124,	2,	'Botswana',	'Repubblica del Botswana',	'BW',	'BWA',	NULL,	NULL),
(125,	6,	'Brasile',	'Repubblica Federale del Brasile',	'BR',	'BRA',	NULL,	NULL),
(126,	2,	'Camerun',	'Repubblica del Camerun',	'CM',	'CMR',	NULL,	NULL),
(127,	6,	'Cile',	'Repubblica del Cile',	'CL',	'CHL',	NULL,	NULL),
(128,	6,	'Colombia',	'Repubblica di Colombia',	'CO',	'COL',	NULL,	NULL),
(129,	6,	'Costa Rica',	'Repubblica di Costa Rica',	'CR',	'CRI',	NULL,	NULL),
(130,	6,	'Cuba',	'Repubblica di Cuba',	'CU',	'CUB',	NULL,	NULL),
(131,	6,	'Dominica',	'Commonwealth di Dominica',	'DM',	'DMA',	NULL,	NULL),
(132,	6,	'Ecuador',	'Repubblica dell\'Ecuador',	'EC',	'ECU',	NULL,	NULL),
(133,	6,	'El Salvador',	'Repubblica di El Salvador',	'SV',	'SLV',	NULL,	NULL),
(134,	2,	'Eritrea',	'',	'ER',	'ERI',	NULL,	NULL),
(135,	2,	'Etiopia',	'Repubblica Democratica Federale d\'Etiopia',	'ET',	'ETH',	NULL,	NULL),
(136,	5,	'Figi',	'Repubblica delle Isole Figi',	'FJ',	'FJI',	NULL,	NULL),
(137,	1,	'Georgia',	'',	'GE',	'GEO',	NULL,	NULL),
(138,	2,	'Ghana',	'Repubblica del Ghana',	'GH',	'GHA',	NULL,	NULL),
(139,	4,	'Guatemala',	'Repubblica del Guatemala',	'GT',	'GTM',	NULL,	NULL),
(140,	2,	'Guinea',	'Repubblica di Guinea',	'GN',	'GIN',	NULL,	NULL),
(141,	2,	'Guinea Equatoriale',	'Repubblica della Guinea Equatoriale',	'GQ',	'GNQ',	NULL,	NULL),
(142,	6,	'Guyana',	'Repubblica Cooperativa della Guyana',	'GY',	'GUY',	NULL,	NULL),
(143,	4,	'Honduras',	'Repubblica dell\'Honduras',	'HN',	'HND',	NULL,	NULL),
(144,	3,	'Iran',	'Repubblica Islamica dell\'Iran',	'IR',	'IRN',	NULL,	NULL),
(145,	3,	'Iraq',	'Repubblica dell\'Iraq',	'IQ',	'IRQ',	NULL,	NULL),
(146,	5,	'Isole Marshall',	'Repubblica delle Isole Marshall',	'MH',	'MHL',	NULL,	NULL),
(147,	5,	'Isole Salomone',	'',	'SB',	'SLB',	NULL,	NULL),
(148,	2,	'Kenya',	'Repubblica del Kenya',	'KE',	'KEN',	NULL,	NULL),
(149,	3,	'Kuwait',	'Stato del Kuwait',	'KW',	'KWT',	NULL,	NULL),
(150,	2,	'Libano',	'Repubblica Libanese',	'LB',	'LBN',	NULL,	NULL),
(151,	2,	'Libia',	'Stato della Libia',	'LY',	'LBY',	NULL,	NULL),
(152,	5,	'Micronesia',	'Stati Federati di Micronesia',	'FM',	'FSM',	NULL,	NULL),
(153,	1,	'Montenegro',	'Repubblica del Montenegro',	'ME',	'MNE',	NULL,	NULL),
(154,	2,	'Mozambico',	'Repubblica del Mozambico',	'MZ',	'MOZ',	NULL,	NULL),
(155,	5,	'Nauru',	'Repubblica di Nauru',	'NR',	'NRU',	NULL,	NULL),
(156,	3,	'Nepal',	'Repubblica Federale Democratica del Nepal',	'NP',	'NPL',	NULL,	NULL),
(157,	4,	'Nicaragua',	'Repubblica del Nicaragua',	'NI',	'NIC',	NULL,	NULL),
(158,	2,	'Niger',	'Repubblica del Niger',	'NE',	'NER',	NULL,	NULL),
(159,	2,	'Nigeria',	'Repubblica Federale della Nigeria',	'NG',	'NGA',	NULL,	NULL),
(160,	3,	'Oman',	'Sultanato di Oman',	'OM',	'OMN',	NULL,	NULL),
(161,	5,	'Palau',	'Repubblica di Palau',	'PW',	'PLW',	NULL,	NULL),
(162,	6,	'Paraguay',	'Repubblica del Paraguay',	'PY',	'PRY',	NULL,	NULL),
(163,	6,	'Perù',	'Repubblica del Perù',	'PE',	'PER',	NULL,	NULL),
(164,	2,	'Repubblica Centroafricana',	'Repubblica Centrafricana',	'CF',	'CAF',	NULL,	NULL),
(165,	2,	'Repubblica del Congo',	'',	'CG',	'COG',	NULL,	NULL),
(166,	2,	'Repubblica Democratica del Congo',	'',	'CD',	'COD',	NULL,	NULL),
(167,	4,	'Repubblica Dominicana',	'',	'DO',	'DOM',	NULL,	NULL),
(168,	2,	'Ruanda',	'Repubblica del Ruanda',	'RW',	'RWA',	NULL,	NULL),
(169,	4,	'Saint Vincent e Grenadine',	'',	'VC',	'VCT',	NULL,	NULL),
(170,	5,	'Samoa',	'Stato Indipendente di Samoa',	'WS',	'WSM',	NULL,	NULL),
(171,	1,	'San Marino',	'Serenissima Repubblica di San Marino',	'SM',	'SMR',	NULL,	NULL),
(172,	2,	'Senegal',	'Repubblica del Senegal',	'SN',	'SEN',	NULL,	NULL),
(173,	1,	'Serbia',	'Repubblica di Serbia',	'RS',	'SRB',	NULL,	NULL),
(174,	2,	'Sierra Leone',	'Repubblica della Sierra Leone',	'SL',	'SLE',	NULL,	NULL),
(175,	3,	'Singapore',	'Repubblica di Singapore',	'SG',	'SGP',	NULL,	NULL),
(176,	3,	'Siria',	'Repubblica Araba di Siria',	'SY',	'SYR',	NULL,	NULL),
(177,	1,	'Slovacchia',	'Repubblica Slovacca',	'SK',	'SVK',	NULL,	NULL),
(178,	1,	'Slovenia',	'Repubblica di Slovenia',	'SI',	'SVN',	NULL,	NULL),
(179,	2,	'Somalia',	'Repubblica Federale di Somalia',	'SO',	'SOM',	NULL,	NULL),
(180,	1,	'Spagna',	'Regno di Spagna',	'ES',	'ESP',	NULL,	NULL),
(181,	3,	'Sri Lanka',	'Repubblica Democratica Socialista dello Sri Lanka',	'LK',	'LKA',	NULL,	NULL),
(182,	2,	'Sudafrica',	'Repubblica del Sudafrica',	'ZA',	'ZAF',	NULL,	NULL),
(183,	2,	'Sudan',	'Repubblica del Sudan',	'SD',	'SDN',	NULL,	NULL),
(184,	2,	'Sudan del Sud',	'Repubblica del Sudan del Sud',	'SS',	'SSD',	NULL,	NULL),
(185,	6,	'Suriname',	'Repubblica del Suriname',	'SR',	'SUR',	NULL,	NULL),
(186,	1,	'Svizzera',	'Confederazione Svizzera',	'CH',	'CHE',	NULL,	NULL),
(187,	2,	'Swaziland',	'Regno dello Swaziland',	'SZ',	'SWZ',	NULL,	NULL),
(188,	3,	'Tagikistan',	'Repubblica del Tagikistan',	'TJ',	'TJK',	NULL,	NULL),
(189,	3,	'Thailandia',	'Regno di Thailandia',	'TH',	'THA',	NULL,	NULL),
(190,	3,	'Taiwan',	'Repubblica di Cin',	'TW',	'TWN',	NULL,	NULL),
(191,	5,	'Tanzania',	'Repubblica Unita di Tanzania',	'TZ',	'TZA',	NULL,	NULL),
(192,	3,	'Timor Est',	'Repubblica Democratica di Timor Est',	'TL',	'TLS',	NULL,	NULL),
(193,	2,	'Togo',	'Repubblica Togolese',	'TG',	'TGO',	NULL,	NULL),
(194,	5,	'Tonga',	'Regno di Tonga',	'TO',	'TON',	NULL,	NULL),
(195,	6,	'Trinidad e Tobago',	'Repubblica di Trinidad e Tobago',	'TT',	'TTO',	NULL,	NULL),
(196,	2,	'Tunisia',	'Repubblica Tunisina',	'TN',	'TUN',	NULL,	NULL),
(197,	1,	'Turchia',	'Repubblica di Turchia',	'TR',	'TUR',	NULL,	NULL),
(198,	3,	'Turkmenistan',	'',	'TM',	'TKM',	NULL,	NULL),
(199,	5,	'Tuvalu',	'',	'TV',	'TUV',	NULL,	NULL),
(200,	1,	'Ucraina',	'',	'UA',	'UKR',	NULL,	NULL),
(201,	2,	'Uganda',	'Repubblica dell\'Uganda',	'UG',	'UGA',	NULL,	NULL),
(202,	6,	'Uruguay',	'Repubblica Orientale dell\'Uruguay',	'UY',	'URY',	NULL,	NULL),
(203,	3,	'Uzbekistan',	'Repubblica dell\'Uzbekistan',	'UZ',	'UZB',	NULL,	NULL),
(204,	5,	'Vanuatu',	'Repubblica di Vanuatu',	'VU',	'VUT',	NULL,	NULL),
(205,	6,	'Venezuela',	'Repubblica Bolivariana del Venezuela',	'VE',	'VEN',	NULL,	NULL),
(206,	3,	'Vietnam',	'Repubblica Socialista del Vietnam',	'VN',	'VNM',	NULL,	NULL),
(207,	3,	'Yemen',	'Repubblica dello Yemen',	'YE',	'YEM',	NULL,	NULL),
(208,	2,	'Zambia',	'Repubblica dello Zambia',	'ZM',	'ZMB',	NULL,	NULL),
(209,	2,	'Zimbabwe',	'Repubblica dello Zimbabwe',	'ZW',	'ZWE',	NULL,	NULL),
(210,	2,	'Zaire',	'Cambio denominazione della Repubblica dello Zaire in Repubblica democratica del Congo',	NULL,	NULL,	'463',	'1997-05-17'),
(211,	2,	'Swaziland',	'Cambio denominazione del Regno dello Swaziland in Regno di Eswatini',	NULL,	NULL,	'456',	'2018-04-19'),
(212,	1,	'Ex Repubblica Jugoslava di Macedonia',	'Cambio denominazione della Ex Repubblica Jugoslava di Macedonia in Repubblica della Macedonia del Nord (denominazione breve Mace',	NULL,	NULL,	'253',	'2019-02-14'),
(213,	4,	'Anguilla',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'917',	'2017-04-13'),
(214,	1,	'Antille olandesi, isole',	'Territorio soppresso e passato a costituire i nuovi territori di Curaçao e Sint Maarten (NL)',	NULL,	NULL,	'907',	'2015-01-01'),
(215,	4,	'Aruba',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'926',	'2017-04-13'),
(216,	4,	'Bermuda',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'908',	'2017-04-13'),
(217,	1,	'Cecoslovacchia',	'Costituite le nazioni della Repubblica ceca e della Slovacchia a seguito del distacco dei territori dal soppresso Stato della Ce',	NULL,	NULL,	'801',	'1992-12-31'),
(218,	1,	'Gibilterra',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'910',	'2017-04-13'),
(219,	4,	'Groenlandia',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'934',	'2017-04-13'),
(220,	1,	'Guernsey',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'940',	'2017-04-13'),
(221,	1,	'Isola di Man',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'959',	NULL),
(222,	4,	'Isole Cayman',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'911',	'2017-04-13'),
(223,	5,	'Isole Cook (NZ)',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'909',	'2017-04-13'),
(224,	1,	'Isole Fær Øer',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'924',	'2017-04-13'),
(225,	4,	'Isole Falkland (Malvine)',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'958',	'2017-04-13'),
(226,	1,	'Isole Jersey',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'925',	'2014-01-01'),
(227,	1,	'Repubblica Socialista Federale di Jugoslavia',	'Soppressa la Repubblica Socialista Federale della Jugoslavia in luogo del nuovo Stato di Serbia e Montenegro',	NULL,	NULL,	'820',	'2003-02-04'),
(228,	1,	'Kosovo',	'Nuovo Stato del Kosovo costituito a seguito del distacco dal territorio dalla Serbia',	NULL,	NULL,	'272',	'2008-02-17'),
(229,	4,	'Montserrat',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'964',	'2017-04-13'),
(230,	5,	'Nuova Caledonia',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'902',	'2017-04-13'),
(231,	5,	'Polinesia francese',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'920',	'2017-04-13'),
(232,	2,	'Sahara occidentale',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'905',	'2017-04-13'),
(233,	4,	'Saint-Barthélemy',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'906',	'2017-04-13'),
(234,	4,	'Saint-Martin (FR)',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'904',	'2017-04-13'),
(235,	1,	'Sark',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'939',	'2017-04-13'),
(236,	1,	'Serbia e Montenegro',	'Costituite le nazioni indipendenti della Serbia e del Montenegro a seguito del distacco del Montenegro dal soppresso Stato della',	NULL,	NULL,	'224',	'2006-06-03'),
(237,	4,	'Sint Maarten (NL)',	'Territorio incluso nella classificazione in adeguamento alle direttive di Eurostat',	NULL,	NULL,	'928',	'2017-04-13')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_continente` = VALUES(`id_continente`), `nome` = VALUES(`nome`), `note` = VALUES(`note`), `iso31661alpha2` = VALUES(`iso31661alpha2`), `iso31661alpha3` = VALUES(`iso31661alpha3`), `codice_istat` = VALUES(`codice_istat`), `data_archiviazione` = VALUES(`data_archiviazione`);

INSERT INTO `task` (`id`, `minuto`, `ora`, `giorno_del_mese`, `mese`, `giorno_della_settimana`, `settimana`, `task`, `iterazioni`, `delay`, `token`, `timestamp_esecuzione`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'_src/_api/_task/_images.resize.php',	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'_src/_api/_task/_mail.queue.send.php',	3,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'_src/_api/_task/_sms.queue.send.php',	3,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'_src/_api/_task/_indirizzi.geocode.php',	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	6,	2,	6,	2,	NULL,	NULL,	'_src/_api/_task/_comuni.importazione.start.php',	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(6,	6,	6,	6,	6,	NULL,	NULL,	'_src/_api/_task/_settori.importazione.start.php',	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `minuto` = VALUES(`minuto`), `ora` = VALUES(`ora`), `giorno_del_mese` = VALUES(`giorno_del_mese`), `mese` = VALUES(`mese`), `giorno_della_settimana` = VALUES(`giorno_della_settimana`), `settimana` = VALUES(`settimana`), `task` = VALUES(`task`), `iterazioni` = VALUES(`iterazioni`), `delay` = VALUES(`delay`), `token` = VALUES(`token`), `timestamp_esecuzione` = VALUES(`timestamp_esecuzione`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `tipologie_anagrafica` (`id`, `id_genitore`, `ordine`, `nome`, `html_entity`, `font_awesome`, `se_persona_fisica`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	10,	'persone fisiche',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	20,	'persone giuridiche',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	1,	10,	'sig.',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL),
(4,	1,	20,	'sig.ra',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL),
(5,	2,	10,	'spett.',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_persona_fisica` = VALUES(`se_persona_fisica`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `tipologie_attivita` (`id`, `id_genitore`, `ordine`, `nome`, `html_entity`, `font_awesome`, `se_anagrafica`, `se_agenda`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	NULL,	'lavoro',	NULL,	NULL,	1,	1,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	NULL,	'ferie',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	NULL,	'permessi',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	NULL,	'malattie',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_anagrafica` = VALUES(`se_anagrafica`), `se_agenda` = VALUES(`se_agenda`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `tipologie_contatti` (`id`, `id_genitore`, `ordine`, `nome`, `html_entity`, `font_awesome`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	NULL,	'di persona',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	NULL,	'telefono',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	NULL,	'mail',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	NULL,	'form web',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(5,	NULL,	NULL,	'chat',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `tipologie_indirizzi` (`id`, `id_genitore`, `ordine`, `nome`, `html_entity`, `font_awesome`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	NULL,	'via',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	NULL,	'viale',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	NULL,	'piazza',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `tipologie_pubblicazioni` (`id`, `id_genitore`, `ordine`, `nome`, `html_entity`, `font_awesome`, `se_bozza`, `se_pubblicato`, `se_evidenza`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	NULL,	'bozza',	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	NULL,	'pubblicato',	NULL,	NULL,	NULL,	1,	NULL,	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `se_bozza` = VALUES(`se_bozza`), `se_pubblicato` = VALUES(`se_pubblicato`), `se_evidenza` = VALUES(`se_evidenza`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);

INSERT INTO `tipologie_telefoni` (`id`, `id_genitore`, `ordine`, `nome`, `html_entity`, `font_awesome`, `id_account_inserimento`, `timestamp_inserimento`, `id_account_aggiornamento`, `timestamp_aggiornamento`) VALUES
(1,	NULL,	10,	'telefono',	'&#xf095;',	'',	NULL,	NULL,	NULL,	NULL),
(2,	NULL,	20,	'mobile',	'&#xf10b;',	'',	NULL,	NULL,	NULL,	NULL),
(3,	NULL,	30,	'fax',	'&#xf02f;',	'',	NULL,	NULL,	NULL,	NULL),
(4,	NULL,	40,	'telefono/fax',	'&#xf1ac;',	'',	NULL,	NULL,	NULL,	NULL)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_genitore` = VALUES(`id_genitore`), `ordine` = VALUES(`ordine`), `nome` = VALUES(`nome`), `html_entity` = VALUES(`html_entity`), `font_awesome` = VALUES(`font_awesome`), `id_account_inserimento` = VALUES(`id_account_inserimento`), `timestamp_inserimento` = VALUES(`timestamp_inserimento`), `id_account_aggiornamento` = VALUES(`id_account_aggiornamento`), `timestamp_aggiornamento` = VALUES(`timestamp_aggiornamento`);
